### ISSUE TITLE
Title: Do The Same For Fonts Too?

### ISSUE THREAD

**Issue by tvraman** [protesilaos/modus-themes#1]
Description: First off, kudos on an awesome piece of work from an
Accessibility perspective. Now that Emacs has  harfbuz  as a
text-shaping engine, the font choices on Linux are rich and
high-quality. This presents an opportunity to create a theme that also
picks the right font for low-vision users, users with dislexia
etc. Note that there is no single font choice for   all category of
users, but providing a  small set of choices that have been tried
might get more users   with special users tarted. Note: I myself
cannot see at all -- I use speech output exclusively, but the number
of users who benefit from color and font accessibility far outnumber
totally blind users.

**Comment by protesilaos** [comment]
Thank you for your feedback! Every improvement on the accessibility front is a step in the right direction.

I do not have sufficient typographic knowledge, nor I am sure how your suggestion could be materialised. Do you think this should be a package? Or perhaps a set of guidelines? Maybe something else?
