### ISSUE TITLE
Highlight the entirety of the code block between #+BEGIN and #+END_SRC

### ISSUE THREAD

**Issue by PurpleAzurite** [protesilaos/modus-themes#10]
Currently, highlights only apply to the tags themselves, but I believe highlighting the entire code block would greatly improve readability across the org document.

![prot](https://user-images.githubusercontent.com/48709923/134464412-47bfd3c1-1b5a-4983-b67f-dfd4c5181fef.png)
t.

**Comment by protesilaos** [comment]
Hello @PurpleAzurite!  There is a customisation option for that: `modus-themes-org-blocks`.

Try it with this:

```elisp
(setq modus-themes-org-blocks 'gray-background)
```

(reload the theme for customisations to take effect)

**Comment by protesilaos** [comment]
Also, if you have the manual of the themes installed (which should normally be the case), evaluate this form to read about some more variables that affect those blocks:

```
(info "(modus-themes) Org mode blocks")
```

**Comment by PurpleAzurite** [comment]
Thank you for the reply. I should've RTFM, I consider this issue resolved now :)

**Comment by protesilaos** [comment]
You are welcome!
