### ISSUE TITLE
Modus Vivendi does not respond to mode line color customization but Modus-vivendi-deuteranope does

### ISSUE THREAD

**Issue by lngndvs** [protesilaos/modus-themes#103]
I will apologize in advance for not being able to explain in a more direct manner the problem I am experiencing.

Some months ago, on Sacha Chua's web pages, an innovation was posted to make modus-themes' Mode Line stand out on active windows.  It did not work on Modus-vivendi, but did work on Modus-vivendi-deuteranope.  I did not follow up.

Recently, I have encounted another issue, this time changing Denote filename colors to my liking.  I am not a programmer, but I was able to successfully make the Date--Time string in the filename less intense.  In the process, I discovered a similar failure of Modus-vivendi to recognize an overriding change, but Modus-vivendi-deuteranope did respond.  When I inspected the source code for the two relevant files, I noted some parameters are missing from modus-vivendi.el (I think this is the correct name).  Or, more likely, and also truly, I am not able to follow the logic of the setting of theme colors.

I have not gone back to the original mode-line code, and found, again, that it works as intended.  This is the code:

;;; Begin
(defun my-update-active-mode-line-colors ()
  (set-face-attribute
   'mode-line nil
   :foreground (modus-themes-get-color-value 'fg-mode-line-active)
	 :background (modus-themes-get-color-value 'bg-magenta-intense)
	 :background (modus-themes-get-color-value 'blue)
	 
   :box '(:line-width
          1
          :color
          (modus-themes-get-color-value 'border-mode-line-active))))
;;
;;; The following hook activates the change.  I used straight.el to install modus-themes.

(use-package modus-themes
	:hook
	(modus-themes-after-load-theme . my-update-active-mode-line-colors))

;;; END

I hope this is helpful.

Alan Davis

**Comment by lngndvs** [comment]
| I have not gone back to the original mode-line code

This is a typo:  I did go back to the original.

**Comment by protesilaos** [comment]
Hello there!

Instead of writing custom code, you can read the manual of the modus-themes. For example, this section shows some sample palette overrides: https://protesilaos.com/emacs/modus-themes#h:e8d781be-eefc-4a81-ac4e-5ed156190df7

Please let me know if that works for you.
