### ISSUE TITLE
Error when running `org-html-htmlize-generate-css`. Invalid face: `modus-themes-variable-pitch`

### ISSUE THREAD

**Issue by 8dcc** [protesilaos/modus-themes#106]
When running `M-x org-html-htmlize-generate-css`, the function fails with the following error message:

```
face-attribute: Invalid face: modus-themes-variable-pitch
```

I tried looking inside `modus-themes.el` and I only saw it being used in a couple of places like:

https://github.com/protesilaos/modus-themes/blob/d2762db19ed48bd0cbba61c41940be479760a35e/modus-themes.el#L1771

But never actually defined. I tried replacing those occurrences with `modus-themes-variable-pitch-ui`, but basically the same error appears:

```
face-attribute: Invalid face: modus-themes-variable-pitch-ui
```

Not sure if this is an issue with the theme or with the `org-html-htmlize-generate-css` function.

**Comment by 8dcc** [comment]
Updating the `emacs-htmlize` package to commit `ed5e5b05fd260e8f161a488d56f10e7f6e01fb75` fixed it.

**Comment by protesilaos** [comment]
> From: 8dcc  ***@***.***>
> Date: Sun,  2 Jun 2024 08:02:22 -0700
>
> Updating the `emacs-htmlize` package to commit `ed5e5b05fd260e8f161a488d56f10e7f6e01fb75` fixed it.

I am curious what is happening here. You are right that
modus-themes-variable-pitch is not defined. There has to be something
wrong with modus-themes.el as well.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by 8dcc** [comment]
If you are curious, the old `emacs-htmlize` version was `dd27bc3f26efd728f2b1f01f9e4ac4f61f2ffbf9`. This is the [full diff](https://github.com/hniksic/emacs-htmlize/compare/dd27bc3f26efd728f2b1f01f9e4ac4f61f2ffbf9..ed5e5b05fd260e8f161a488d56f10e7f6e01fb75) of the two commits, but it's pretty big.
