### ISSUE TITLE
Transparent titlebars on MacOS not using 'darker' color like ef-themes

### ISSUE THREAD

**Issue by kazuwal** [protesilaos/modus-themes#109]
ef-themes use bg-dim (i think) for transparent titlebars on Mac. I use [ns-auto-titlebar](https://github.com/purcell/ns-auto-titlebar) with Doom which uses  _frame-background-mode_ to apply the titlebar color. What is ef-themes doing that modus themes is not doing?

![Screenshot 2024-06-17 at 09 21 44](https://github.com/protesilaos/modus-themes/assets/6560983/b6cd144e-5bad-4311-be64-6f044ce65e22)
![Screenshot 2024-06-17 at 09 21 35](https://github.com/protesilaos/modus-themes/assets/6560983/0b148077-54ec-4c7c-9adc-a523ecc77fea)
![Screenshot 2024-06-17 at 09 21 22](https://github.com/protesilaos/modus-themes/assets/6560983/aa3b68aa-75e5-4ee0-8ac2-5895dd0b2dfa)
![Screenshot 2024-06-17 at 09 20 58](https://github.com/protesilaos/modus-themes/assets/6560983/83a9df44-3822-48a9-a17a-071e6d442aa0)

**Comment by protesilaos** [comment]
> From: Gregory Adebesin ***@***.***>
> Date: Tue, 18 Jun 2024 02:56:02 -0700
>
> Closing. I was overriding the title bar color 

Fine!

-- 
Protesilaos Stavrou
https://protesilaos.com
