### ISSUE TITLE
Viper support

### ISSUE THREAD

**Issue by ZharMeny** [protesilaos/modus-themes#115]
Built-in `viper-mode` changes how input text in the minibuffer looks depending on the current input mode, which looks fine with modus-operandi, but quite jarring with modus-vivendi (light background with dark text, while the rest of the screen is dark background with light text), there are also other faces that could benefit from some tweaks.
![Screenshot from 2024-08-06 01-03-48](https://github.com/user-attachments/assets/256fe280-c25b-4a87-b029-e1799b47b576)

**Comment by protesilaos** [comment]
Thank you @ZharMeny! I just added preliminary support for it. Unfortunately, they do not let themes configure the colour of the cursor. The green they use is not optimal for our purposes.

Anyway, please take a look. My intuition was to remove those coloured backgrounds from the minibuffer. They feel out-of-place there as they can be mistaken for the currently selected completion candidate.

**Comment by ZharMeny** [comment]
> Unfortunately, they do not let themes configure the colour of the cursor.

They seem to expose the configurability through `viper-*-cursor-color` variables, anything on that front?

> My intuition was to remove those coloured backgrounds from the minibuffer. They feel out-of-place there as they can be mistaken for the currently selected completion candidate.

They indicate what state Viper is currently in (which is normally indicated in the mode-line, that the minibuffer lacks), and removing them may lead to confusion between Emacs state and Viper state.  This can be avoided by setting `viper-emacs-state-cursor-color` to some distinct colour; the definition of that variable has "Magenta" commented out.

**Comment by protesilaos** [comment]
> From: ZharMeny ***@***.***>
> Date: Tue,  6 Aug 2024 03:42:41 -0700
>
>> Unfortunately, they do not let themes configure the colour of the cursor.
>
> They seem to expose the configurability through `viper-*-cursor-color`
> variables, anything on that front?

Those are defined as 'defcustom', which means that they are "user
options". I generally avoid modifying those at the theme level, though
here we are justified to take action because the defaults are
problematic.

However, we have a problem. The 'viper-vi-state-cursor-color' is an
internal variable, which captures the original value of the cursor
colour. This means that if we change to another Modus theme, we end up
with an awkward colour again.

You can try this by evaluating the following:

    (defun my-modus-themes-viper-cursors (&rest _)
      (modus-themes-with-colors
        (custom-set-variables
         `(viper-replace-overlay-cursor-color ,err)
         `(viper-insert-state-cursor-color ,info)
         `(viper-emacs-state-cursor-color ,fg-main))))

    (add-hook 'enable-theme-functions #'my-modus-themes-viper-cursors)

Then switch to normal mode to see the old default cursor colour. In my
case, I went from a dark theme to a light one and now I cannot see the
cursor.

>> My intuition was to remove those coloured backgrounds from the
>> minibuffer. They feel out-of-place there as they can be mistaken for
>> the currently selected completion candidate.
>
> They indicate what state Viper is currently in (which is normally
> indicated in the mode-line, that the minibuffer lacks), and removing
> them may lead to confusion between Emacs state and Viper state. This
> can be avoided by setting `viper-emacs-state-cursor-color` to some
> distinct colour; the definition of that variable has "Magenta"
> commented out.

My concern with the added backgrounds is that they can be confusing. If
we can get the cursor colours right, then we should be okay.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by ZharMeny** [comment]
> This means that if we change to another Modus theme, we end up with an awkward colour again.
You can try this by evaluating the following:
[...]
Then switch to normal mode to see the old default cursor colour. In my
case, I went from a dark theme to a light one and now I cannot see the
cursor.

This is quite unfortunate, I don't think it would be easy to fix that without modifying Viper itself.  Thank you, anyways.

**Comment by protesilaos** [comment]
I forgot to push the changes the other day. Did it now. Thanks!

About the issue with the default cursor, I think it needs to be reported on the Emacs bug tracker. Since you are using viper, do you want to do it? You can add my email in CC: <info@protesilaos.com>.
