### ISSUE TITLE
Howm support

### ISSUE THREAD

**Issue by jabirali** [protesilaos/modus-themes#117]
First of all, thanks for creating the  Modus themes :).

Recently, I've been enjoying using [Howm](https://github.com/kaorahi/howm). I'm not sure if you're familiar with it; it's a minor mode for managing a personal wiki in Emacs, which can be used together with any plaintext filetype (Org, Markdown, etc.). It has some pretty cool features, like the emphasis on "self-organization" of notes and the ability to create "comefrom links" (as opposed to the more traditional "goto links"). Documentation  is available [here](https://github.com/Emacs101/howm-manual).

Unfortunately, the Modus themes – and most other themes – don't currently theme the faces defined by Howm, and the defaults are IMO quite intense. For instance, here is a screenshot of the Howm note list when viewed using the `modus-operandi-tinted` theme:

<img width="584" alt="Screenshot 2024-09-03 at 16 01 51" src="https://github.com/user-attachments/assets/e35a26f2-1428-4446-85ca-6582dfeeaf84">

Perhaps the Modus themes could alter the faces used for Howm?

**Comment by protesilaos** [comment]
> From: Jabir Ali Ouassou ***@***.***>
> Date: Wed,  4 Sep 2024 13:58:31 -0700
>
> First of all, thanks for creating the  Modus themes :).

You are welcome!

> Recently, I've been enjoying using
> [Howm](https://github.com/kaorahi/howm). I'm not sure if you're
> familiar with it; it's a minor mode for managing a personal wiki in
> Emacs, which can be used together with any plaintext filetype (Org,
> Markdown, etc.). It has some pretty cool features, like the emphasis
> on "self-organization" of notes and the ability to create "comefrom
> links" (as opposed to the more traditional "goto links").
> Documentation is available
> [here](https://github.com/Emacs101/howm-manual).

I have heard about it, but never used it.

> Unfortunately, the Modus themes – and most other themes – don't
> currently theme the faces defined by Howm, and the defaults are IMO
> quite intense. For instance, here is a screenshot of the Howm note
> list when viewed using the `modus-operandi-tinted` theme:
>
> <img width="584" alt="Screenshot 2024-09-03 at 16 01 51" src="https://github.com/user-attachments/assets/e35a26f2-1428-4446-85ca-6582dfeeaf84">
>
> Perhaps the Modus themes could alter the faces used for Howm?

In principle, yes. Though the problem here is that I have not used the
package and using it is not trivial work. Do you have a basic setup that
shows all the faces howm defines? I need to check them in context.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by jabirali** [comment]
Thanks! I'd be happy to help out with this if needed :).

If you install Howm from MELPA, this is a minimal configuration (without integration with Org-mode etc.):
```emacs-lisp
(use-package howm
  :bind
  ("<f12>" . howm-list-all)
  ("<C-f12>" . howm-create)
  :config
  (setq howm-directory "~/howm")
  (setq howm-home-directory howm-directory))
```
With this setup, if you press `C-F12`, It should create a new note as a `txt` file in the directory `~/howm`. On top of the basic `text-mode`, it adds some highlighting if you type e.g. this in:

<img width="232" alt="image" src="https://github.com/user-attachments/assets/99f41db3-d34c-4a0d-9790-38f6a37e33a0">

- The note title is marked in `howm-mode-title-face`
- Today's date is marked in `howm-reminder-today-face`. Both today's date and other dates are in addition marked in `action-lock-face` (here: underline), which is used for all Howm "links".
- The "goto link" is marked in `howm-mode-ref-face` (this is used like a search-based "fuzzy link")
- The "comefrom link" is in `howm-mode-keyword-face` (this is used kinda like a "tag" in practice)
- The "wikilink" is marked in `howm-mode-wiki-face` (this is used like an "exact link" to a note)

If you then save the note, you can then with this setup press F12 to bring up the list of notes:

<img width="364" alt="image" src="https://github.com/user-attachments/assets/68c52a35-bd40-4ef7-9e33-00d6f594e1d5">

- The filename is marked as `howm-view-name-face`

Then you can press "g this RET" to grep for "this" in the notes:

<img width="430" alt="image" src="https://github.com/user-attachments/assets/86f56c70-195e-421e-8ea4-d98b812c54e3">

- Each search hit is now marked in `howm-view-hilit-face`
- When there are multiple hits in one file, the "filename" part of the note list is marked in `howm-view-empty-face` in the lines below (the dark area).

From my point of view, I think these are the most important faces.

But I haven't used Howm's GTD system, which uses a few more faces (the `howm-reminder-*` set of faces). Based on the manual, I think this example shows most of those faces – note that both the date (days to/from today) and the symbol after (the `+-@!.~`) seems to affect the faces used here.

<img width="385" alt="image" src="https://github.com/user-attachments/assets/6927b828-3d6a-4e34-91e0-6cf72ec6fcb1">


I hope this helps!

**Comment by protesilaos** [comment]
Can you please evaluate this and give it a try?

```elisp
(defun my-modus-themes-faces (&rest _)
  (modus-themes-with-colors
    (custom-set-faces
     `(action-lock-face ((,c :inherit button)))
     `(howm-mode-keyword-face (( )))
     `(howm-mode-ref-face ((,c :inherit link)))
     `(howm-mode-title-face ((,c :inherit modus-themes-heading-0)))
     `(howm-mode-wiki-face ((,c :inherit link)))
     `(howm-reminder-deadline-face ((,c :foreground ,date-deadline)))
     `(howm-reminder-late-deadline-face ((,c :inherit bold :foreground ,date-deadline)))
     `(howm-reminder-defer-face ((,c :foreground ,date-scheduled)))
     `(howm-reminder-scheduled-face ((,c :foreground ,date-scheduled)))
     `(howm-reminder-done-face ((,c :foreground ,prose-done)))
     `(howm-reminder-todo-face ((,c :foreground ,prose-todo)))
     `(howm-reminder-normal-face ((,c :foreground ,date-common)))
     `(howm-reminder-today-face ((,c :inherit bold :foreground ,date-common)))
     `(howm-reminder-tomorrow-face ((,c :inherit bold :foreground ,date-scheduled)))
     `(howm-simulate-todo-mode-line-face ((,c :inherit bold)))
     `(howm-view-empty-face (( )))
     `(howm-view-hilit-face ((,c :inherit match)))
     `(howm-view-name-face ((,c :inherit bold)))
     `(iigrep-counts-face1 ((,c :foreground ,rainbow-1)))
     `(iigrep-counts-face2 ((,c :foreground ,rainbow-2)))
     `(iigrep-counts-face3 ((,c :foreground ,rainbow-3)))
     `(iigrep-counts-face4 ((,c :foreground ,rainbow-4)))
     `(iigrep-counts-face5 ((,c :foreground ,rainbow-5))))))

(add-hook 'enable-theme-functions #'my-modus-themes-faces)
```

**Comment by jabirali** [comment]
Thanks for the quick response and the code!

I tested it now with the same example files as above. Here are a few different screenshots using different Modus variants (this time in GUI to check that no terminal quirks interfere):

<img width="868" alt="Screenshot 2024-09-05 at 12 17 37" src="https://github.com/user-attachments/assets/da4d557b-c6a5-4827-bac6-a643ff25cf02">

<img width="868" alt="Screenshot 2024-09-05 at 12 16 48" src="https://github.com/user-attachments/assets/c626f147-f576-43ab-a205-3324bacf16b3">

<img width="868" alt="Screenshot 2024-09-05 at 12 18 00" src="https://github.com/user-attachments/assets/cdd7ec29-99d0-49b2-b5d6-c75aa9d58581">

<img width="868" alt="Screenshot 2024-09-05 at 12 18 09" src="https://github.com/user-attachments/assets/3bfbfa5d-9db0-481c-87ef-23724841d87f">

Some comments:

- The core features I use now look excellent – it's much more consistent with the highlighting used in e.g. Org-mode, and the new colors are much easier on the eyes.
- In "comefrom links", there is a "gap" between the `<<<` and the name. However, `C-u C-x =` reveals that this gap is simply not fontified by `howm-mode`. I'm not sure if the best course of action is to keep the current highlighting and report this as an issue upstream in `howm-mode`, or to use a different `howm-mode-keyword-face` (e.g. default foreground face without underline like the wikilink brackets).
- It seems the underline below the reminder faces are all shown in blue rather than matching the text it underlines. (Presumably due to the order in which `howm-mode` applies faces?) It might be nicer to either change the underline color to match the text or disable them in this context.
- I didn't show the "grep" above, but that looks great now.

**Comment by protesilaos** [comment]
> From: Jabir Ali Ouassou ***@***.***>
> Date: Thu,  5 Sep 2024 03:42:23 -0700
>
> Thanks for the quick response and the code!

You are welcome!

> [... 12 lines elided]

> Some comments:
>
> - The core features I use now look excellent – it's much more
> consistent with the highlighting used in e.g. Org-mode, and the new
> colors are much easier on the eyes.

Very well!

> - In "comefrom links", there is a "gap" between the `<<<` and the
> name. However, `C-u C-x =` reveals that this gap is simply not
> fontified by `howm-mode`. I'm not sure if the best course of action is
> to keep the current highlighting and report this as an issue upstream
> in `howm-mode`, or to use a different `howm-mode-keyword-face` (e.g.
> default foreground face without underline like the wikilink brackets).

I am fine either way. Though I think it is worth asking the maintainer
about this.

> - It seems the underline below the reminder faces are all shown in
> blue rather than matching the text it underlines. (Presumably due to
> the order in which `howm-mode` applies faces?) It might be nicer to
> either change the underline color to match the text or disable them in
> this context.

The underline comes from another face. I do not remember now if it is
'action-lock-face' or 'howm-mode-ref-face'. My problem is that I do not
know all the contexts where those are used.

> - I didn't show the "grep" above, but that looks great now.

Good!

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by jabirali** [comment]
> Though I think it is worth asking the maintainer
about this.

@kaorahi: Above, we have had a discussion about adding support for Howm to the Modus themes, such that consistent colors and faces are used to fontify Howm buffers as are used for e.g. Org-mode and Markdown-mode. Prot has made a nice suggestion above for how to set it up (and added it to the newest version of the docs), see my last post above for some screenshots of how the current version looks.

Perhaps you have some input or insights to add, regarding how to best theme Howm-mode?

For example, what might be the best way to handle reminder faces, which currently inherit a blue underline from the action-lock face (which are now themed as normal links)?

**Comment by kaorahi** [comment]
Thanks for another modernization!

Unfortunately, I'm not really the type of person who cares much about aesthetics, and I don't have enough ability or interest to give useful feedback on this. That said, users would definitely appreciate it if you suggest a better color scheme.

It seems we need the following patch to modify the underline style in reminders (not well tested).

https://github.com/kaorahi/howm/tree/modus117_underline

```emacs-lisp
(setq howm-reminder-underline-face nil)  ;; default action-lock color
(setq howm-reminder-underline-face '(:underline nil))  ;; no underline
(setq howm-reminder-underline-face '(:underline t))  ;; inherit reminder color
```

Personally, I prefer using the action-lock color for all action-lock underlines, even in reminders, but I know my aesthetic sense is broken. :p

**Comment by kaorahi** [comment]
Is `howm-menu-key-face` missing?
https://github.com/kaorahi/howm/blob/69445111403cf4b99b8912392130411df7f91d77/howm-vars.el#L1123

To remove the underlines in reminders, how about simply appending `:underline nil`?

```emacs-lisp
     `(howm-reminder-deadline-face ((,c :foreground ,date-deadline :underline nil)))
```

If this is enough, we don't need the dirty patch in my previous post.

**Comment by jabirali** [comment]
@kaorahi: Thanks a lot for chiming in! :)

Based on your feedback, I have now updated @protesilaos suggestion as follows:
- Added a suggestion for `howm-menu-key-face` (which seems to be used for keybinding hints in the menu);
- Set  `:underline nil` in the reminder faces as suggested (so that you don't need to patch this into Howm itself);
- Fixed a typo in the face name used for scheduled events (`schedule` vs. `scheduled`).

The revised code is then:
```emacs-lisp
(defun my-modus-themes-faces (&rest _)
  (modus-themes-with-colors
    (custom-set-faces
     `(action-lock-face ((,c :inherit button)))
     `(howm-menu-key-face ((,c :inherit help-key-binding)))
     `(howm-mode-keyword-face (( )))
     `(howm-mode-ref-face ((,c :inherit link)))
     `(howm-mode-title-face ((,c :inherit modus-themes-heading-0)))
     `(howm-mode-wiki-face ((,c :inherit link)))
     `(howm-reminder-deadline-face ((,c :foreground ,date-deadline :underline nil)))
     `(howm-reminder-late-deadline-face ((,c :inherit bold :foreground ,date-deadline :underline nil)))
     `(howm-reminder-defer-face ((,c :foreground ,date-scheduled :underline nil)))
     `(howm-reminder-schedule-face ((,c :foreground ,date-scheduled :underline nil)))
     `(howm-reminder-done-face ((,c :foreground ,prose-done :underline nil)))
     `(howm-reminder-todo-face ((,c :foreground ,prose-todo :underline nil)))
     `(howm-reminder-normal-face ((,c :foreground ,date-common :underline nil)))
     `(howm-reminder-today-face ((,c :inherit bold :foreground ,date-common :underline nil)))
     `(howm-reminder-tomorrow-face ((,c :inherit bold :foreground ,date-scheduled :underline nil)))
     `(howm-simulate-todo-mode-line-face ((,c :inherit bold)))
     `(howm-view-empty-face (( )))
     `(howm-view-hilit-face ((,c :inherit match)))
     `(howm-view-name-face ((,c :inherit bold)))
     `(iigrep-counts-face1 ((,c :foreground ,rainbow-1)))
     `(iigrep-counts-face2 ((,c :foreground ,rainbow-2)))
     `(iigrep-counts-face3 ((,c :foreground ,rainbow-3)))
     `(iigrep-counts-face4 ((,c :foreground ,rainbow-4)))
     `(iigrep-counts-face5 ((,c :foreground ,rainbow-5))))))

(add-hook 'enable-theme-functions #'my-modus-themes-faces)
```
Here are two example screenshots showing that the `howm-menu` now renders well (including the keybinding hints):
<img width="683" alt="Screenshot 2024-09-09 at 14 12 49" src="https://github.com/user-attachments/assets/2a47e70c-1cd1-4a4a-8128-eeb6295318c4"><img width="683" alt="Screenshot 2024-09-09 at 14 13 04" src="https://github.com/user-attachments/assets/129e132c-18be-4971-bc08-f5d0c1ecdbb2">
Here are some more examples showing that the reminder faces now don't have the blue line (which I personally prefer):
<img width="837" alt="Screenshot 2024-09-09 at 14 20 19" src="https://github.com/user-attachments/assets/c43ac861-7b52-4cac-a9f4-b03c548a23bd"><img width="837" alt="Screenshot 2024-09-09 at 14 20 30" src="https://github.com/user-attachments/assets/b1456b3e-738b-4200-a8b4-bb884abb3566">
From my point of view, I think this looks perfect :)
