### ISSUE TITLE
FYI: new tab-line-tab-modified face in Emacs 28

### ISSUE THREAD

**Issue by alphapapa** [protesilaos/modus-themes#12]
Hi Prot,

FYI, there's a new face coming in Emacs 28: https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=fcca1db9fd1eb2930f29972e7def0936c3269f1b  It might deserve customization in `modus-themes`.  In `modus-vivendi`, for example, the default inherited face produces a light blue color, which isn't as distinguished as in the default Emacs theme.

**Comment by protesilaos** [comment]
On 2021-09-28, 00:19 -0700, alphapapa ***@***.***> wrote:

> Hi Prot,
>
> FYI, there's a new face coming in Emacs 28:
> https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=fcca1db9fd1eb2930f29972e7def0936c3269f1b
> It might deserve customization in `modus-themes`.  In `modus-vivendi`,
> for example, the default inherited face produces a light blue color,
> which isn't as distinguished as in the default Emacs theme.

Thank you, Adam!

I noticed the discussion on emacs-devel.  Will rebuild from source and
update things accordingly.  I like the faint red you used and think it
is the right fit here.

More to follow.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by protesilaos** [comment]
Done.  Thanks again!

I experimented with different shades of a subtle red and eventually went with the one that has slightly more hints of blue (magenta basically). Just to be prepared for the eventual tab-line-tab-urgent which will need a more saturated red.

Fine margins here:

![2021-09-28_11:17:24_1916x1058](https://user-images.githubusercontent.com/12828033/135050187-dffff0d0-8a84-4cee-846a-49c4c9ee2554.png)
![2021-09-28_11:17:32_1916x1058](https://user-images.githubusercontent.com/12828033/135050188-925184ff-19fc-4465-9be1-55a7193b7ca8.png)

But if we have an urgent face, then we get more flexibility:

![2021-09-28_11:29:29_1916x1058](https://user-images.githubusercontent.com/12828033/135052066-20c7cca2-cd93-438b-a5d3-2aa7f5beb69a.png)
![2021-09-28_11:29:37_1916x1058](https://user-images.githubusercontent.com/12828033/135052076-e90e1d63-6a65-4501-a27b-223c4372c21f.png)

Though we need not worry about that now. We can always edit things afterwards.

**Comment by alphapapa** [comment]
Great, thanks.

I don't know if there will be an urgent face; I guess Emacs would need some kind of system to mark buffers as needing attention first (there is the `tracking` package used by some IRC packages, but it's not part of Emacs).

If there is one someday, I'd hope it would use a box or background color rather than changing the text color.  At least, I would advocate for that.  :)
