### ISSUE TITLE
Question : How to remove this two item?

### ISSUE THREAD

**Issue by thyeun** [protesilaos/modus-themes#122]
Sorry, i'm new to modus themes, May i know how should i remove this two item? 

![photo_6154393977609109053_y](https://github.com/user-attachments/assets/183de06f-59ac-486f-b44a-ecda85788133)

**Comment by protesilaos** [comment]
> From: Thomas Yeun ***@***.***>
> Date: Thu,  7 Nov 2024 19:37:48 -0800
>
> Sorry, i'm new to modus themes, May i know how should i remove this two item? 
>
> ![photo_6154393977609109053_y](https://github.com/user-attachments/assets/183de06f-59ac-486f-b44a-ecda85788133)

The one on the side is called the "fringe" area. Though I suspect you
are also seeing the background of the line numbers. The other at the
bottom is called the "mode line".

Here is how you can hide all those background colours:

    (setq modus-themes-common-palette-overrides
          '(;; Make the fringe not have its own background
            (fringe unspecified)

            ;; Do not use a background for line numbers (current and others)
            (bg-line-number-inactive unspecified)
            (bg-line-number-active unspecified)

            ;; Make the mode lines not have a background
            (bg-mode-line-inactive unspecified)
            (bg-mode-line-active unspecified)))

Evaluate this code and then reload the theme for changes to take effect.

In the manual of the Modus themes we have a lot of examples on how to
use "palette overrides". You can do more with them, such as to change
the colour of the text used in various places. I am happy to help you
with specific examples.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by thyeun** [comment]
Here is my code that been add but still cant hide it.

```
 (use-package modus-themes
     :init (load-theme 'modus-vivendi t))
   (setq modus-themes-mode-line '(moody accented borderless)
        modus-themes-bold-constructs t
        modus-themes-italic-constructs t
        modus-themes-subtle-line-numbers nil
        modus-themes-fringes 'subtle
        modus-themes-mixed-fonts t
        modus-themes-variable-pitch-ui nil
        modus-themes-custom-auto-reload t
        modus-themes-tabs-accented t
        modus-themes-paren-match '(bold intense)
        modus-themes-prompts '(bold intense)
        modus-themes-completions
              '((matches . (extrabold background intense))
               (selection . (semibold accented intense))
               (popup . (accented)))
        modus-themes-org-blocks 'tinted-background
        modus-themes-scale-headings t
        modus-themes-region '(bg-only no-extend)
        modus-themes-headings
             '((1 . (rainbow overline background 1.4))
               (2 . (rainbow background 1.3))
               (3 . (rainbow bold 1.2))
               (t . (semilight 1.1))))

   (setq modus-themes-common-palette-overrides
          '(;; Make the fringe not have its own background
            (fringe unspecified)

            ;; Do not use a background for line numbers (current and others)
            (bg-line-number-inactive unspecified)
            (bg-line-number-active unspecified)

            ;; Make the mode lines not have a background
            (bg-mode-line-inactive unspecified)
            (bg-mode-line-active unspecified)))

```

Did i done something wrong with the suggestion code that provided by you?

**Comment by thyeun** [comment]
Here how it look like used with ```doom theme```. But i cant make it same by using ```modus theme```.

![241108_14h48m40s_screenshot](https://github.com/user-attachments/assets/4f20b708-4ba7-4161-b065-11282dafe68f)

**Comment by protesilaos** [comment]
> From: Thomas Yeun ***@***.***>
> Date: Thu,  7 Nov 2024 22:40:07 -0800
>
> Here is my code that been add but still cant hide it.

Do you know which version of the themes you are using? I notice some
variables in your configuration do not exist anymore: they are from
older versions.

Also, did you reload the theme after setting the palette overrides?

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by thyeun** [comment]
For reload - yes, i even kill emacs and start back the daemon.

For modus-theme version - 20241107.816

**Comment by thyeun** [comment]
Below are the step how i make change and reload.

1. Edit on my Emacs.org with the code that provided in this post previously.
2. kill emacs with ```emacsclient -e "(kill-emacs)" in terminal
3. run ```emacs --daemon```
4. launch emacs with ``` emacsclient -cn```

But still the ```fringe``` appear and the ```mode-line``` still remain no change.

**Comment by thyeun** [comment]
Solve it by adding this line into it ```(add-hook 'after-init-hook (lambda () (load-theme 'modus-vivendi t)))

Dont know why i need that to force the theme to be load like that. but any how it solve this issue.

**Comment by protesilaos** [comment]
> From: Thomas Yeun ***@***.***>
> Date: Fri,  8 Nov 2024 20:00:09 -0800
>
> Solve it by adding this line into it ```(add-hook &#39;after-init-hook
> (lambda () (load-theme &#39;modus-vivendi t)))```
>
> Dont know why i need that to force the theme to be load like that. but
> any how it solve this issue.

The reason is because your 'load-theme' call was inside the :init
keyword, which is too early. Put it in the :config so that it loads
after you 'setq' all the configurations.

-- 
Protesilaos Stavrou
https://protesilaos.com
