### ISSUE TITLE
Light/dark variants for different modes 

### ISSUE THREAD

**Issue by linwaytin** [protesilaos/modus-themes#126]
This might be a strange question. I like to terminal emulators like vterm and eat and programming modes in dark themes, but for org mode and maybe latex mode, I like light themes. 

Currently I use like `face-remap-add-relative` to switch colors in vterm and eat, but this is not quite elegant and it still has some weird issues. Is there a way to solve for this problem?

**Comment by protesilaos** [comment]
> From: linwaytin ***@***.***>
> Date: Thu, 28 Nov 2024 17:34:36 -0800
>
> This might be a strange question. I like to terminal emulators like
> vterm and eat and programming modes in dark themes, but for org mode
> and maybe latex mode, I like light themes.
>
> Currently I use like `face-remap-add-relative` to switch colors in
> vterm and eat, but this is not quite elegant and it still has some
> weird issues. Is there a way to solve for this problem?

No, because themes are designed to be global. Using the remap mechanism
is the way to go. Sure, it is a bit awkward to have to remap lots of
faces, but it is the best we have.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by protesilaos** [comment]
> From: linwaytin ***@***.***>
> Date: Fri, 29 Nov 2024 06:39:44 -0800
>
> Thanks.

You are welcome!

> If so, is it possible to remap a group of faces together? For example,
> can I remap all the faces for org-mode to the definitions in
> `modus-operandi`, when the theme is set to `modus-vivendi`?

Unfortunately this is not sophisticated enough. It works on one face at
a time, which is why it is hard to use at the scale you describe.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by linwaytin** [comment]
Got it. Thank you!
