### ISSUE TITLE
Suggest a add a tab-line custom variable.

### ISSUE THREAD

**Issue by tumashu** [protesilaos/modus-themes#14]
enable this variable, do not use bold and box, all tab-line* font use a height

**Comment by tumashu** [comment]
this will let tab-line size do not change all the time

**Comment by protesilaos** [comment]
Thank you @tumashu!  Can you please show me an example with the tab-line size change?  I am not sure I understand what the issue is.  But yes, we must fix it.

**Comment by tumashu** [comment]
I hard to create a screenshot, the main problem is that, bold and box will let tab width a bit larger, when switch tab, tab looks a abit flicker, different size have similar problem too.

**Comment by protesilaos** [comment]
Is this related to the discussion on emacs-devel about CJK fonts height/width? Because I do not notice any changes in height/width with latin fonts.

Discussion here: https://lists.gnu.org/archive/html/emacs-devel/2021-11/msg00959.html

**Comment by protesilaos** [comment]
Okay, I reproduced the bug.  Yes, it is related to the fonts.

I will make a new option to disable bold and box attributes.

**Comment by protesilaos** [comment]
Actually, I am reviewing it now.  We still have problems with the mode line and possibly other interfaces, so a new variable for the tab-line and related is not the solution.  We need something more general.  I will think about it.

**Comment by tumashu** [comment]
ok

**Comment by protesilaos** [comment]
Hello again!

The real problem here is how Emacs handles different scripts.  I do not know if things have improved in emacs.git as the dicusssion did not have a clear outcome (or it did and I missed it).  We cannot add a variable for tabs as this affects practically every context.
