### ISSUE TITLE
Invalid face attribute :background nil

### ISSUE THREAD

**Issue by Jousimies** [protesilaos/modus-themes#15]
The `Invalid face attribute :background nil` error increase with mouse scroll
My config:
```elisp
(leaf modus-themes
      :doc "https://protesilaos.com/modus-themes/"
      :load-path "~/.emacs.d/site-lisp/packages/modus-themes"
      :require t
      :commands (modus-themes-load-themes)
      :custom ((modus-themes-italic-constructs . t)
	       (modus-themes-bold-constructs . nil)
	       (modus-themes-region . '(bg-only no-extend))
	       (modus-themes-lang-checkers . '(background text-also straight-underline))
	       (modus-themes-links . '(faint))
	       (modus-themes-mode-line . '(accented borderless)))
      :init
      ;; Load the theme files before enabling a theme
      (modus-themes-load-themes)
      )
```
![image](https://user-images.githubusercontent.com/72933939/142716443-65b2dc3c-96ad-422a-8c79-1a589d8c0a9d.png)

**Comment by protesilaos** [comment]
Hello @Jousimies and thanks for taking the time to report this.

I cannot reproduce this on my end.  These are the steps I followed:

1. In a shell prompt type `emacs -Q`
2. Insert the following in the scratch buffer:

```elisp
(require 'modus-themes "~/.emacs.d/site-lisp/packages/modus-themes/modus-themes.el") ; check the path
(setq modus-themes-italic-constructs t)
(setq modus-themes-bold-constructs nil)
(setq modus-themes-region '(bg-only no-extend))
(setq modus-themes-lang-checkers '(background text-also straight-underline))
(setq modus-themes-links '(faint))
(setq modus-themes-mode-line '(accented borderless))

(modus-themes-load-themes)

(load-theme 'modus-operandi t)
```

3. Run `M-x eval-buffer`
4. Now show the buffer with the echo area messages with `C-h e`.
5. Try to scroll up and down.

![2021-11-20_12:17:39_1920x1080](https://user-images.githubusercontent.com/12828033/142722854-ec993372-94bd-4633-ab41-d683e5bf94ea.png)

Can you try those steps and let me know if you get the same results as I do?

If you do, then there must be something wrong with another package that you use and how it expects some background value that does not exist.  Maybe there still is something in the themes, but we need to determine what produces the error.

**Comment by protesilaos** [comment]
I think I found the problem on the side of the themes.  I pushed the changes.  Though there still may be another package involved.

**Comment by Jousimies** [comment]
@protesilaos Thank you for your help.  I found the problem related to the centaur-tabs package.

**Comment by protesilaos** [comment]
Very well! If you can pinpoint it, then we should report it to the centaur-tabs maintainer so that other users do not experience similar problems.

Also, I would be curious to know what it is, just so I can learn what to expect next time something similar happens.

**Comment by jeremyf** [comment]
@Jousimies do you have the solution for this; I'm seeing it in my build as well.

**Comment by protesilaos** [comment]
@jeremyf I am trying to fix the problem upstream: https://github.com/ema2159/centaur-tabs/pull/179.  Basically, the way centaur-tabs' faces are designed right now prevent us from using `:inherit` (which is something that themes should be able to do).

Relevant issue in the GitLab mirror: https://gitlab.com/protesilaos/modus-themes/-/issues/288
