### ISSUE TITLE
Modus operandi shoud use bold when possible

### ISSUE THREAD

**Issue by sidkshatriya** [protesilaos/modus-themes#16]
I'm noticing that the modus operandi theme does not use **bold** very much.

See this snippet of code on the spacemacs light theme:
<img src="https://user-images.githubusercontent.com/638477/147489908-d8fbc8e2-6567-457b-a7b3-7052f52ab7c1.png" width=450 />

Notice that "Vcpu", "Ordering::Release", "VCPU_RTSIG_OFFSET", "handle_signal", "register_kick_signal_handler" **are all in bold**. This makes the code more readable.

In the modus operandi theme **bold** never seems to be used at all:
<img src="https://user-images.githubusercontent.com/638477/147490152-dad74866-bd32-4fa4-bf59-6a0b81597229.png" width=450 />

_Suggestion:_ Modus themes should use **bold** judiciously to give emphasis to things like function names, module names, constants etc.

**Comment by protesilaos** [comment]
Hello @sidkshatriya and thanks for reporting this!

Have you tried the customisation option `modus-themes-bold-constructs`?

```elisp
(setq modus-themes-bold-constructs t)
```

The manual covers all the customisation options (there are lots of them).  Read it here: https://protesilaos.com/emacs/modus-themes

Or evaluate this from inside Emacs: 

```
(info "(modus-themes) Top")
```

**Comment by protesilaos** [comment]
Same for italics, by the way:

```elisp
(setq modus-themes-italic-constructs t)
```

**Comment by sidkshatriya** [comment]
Hi @protesilaos, I added the setq for bold constructions and italic constructs but for some reason it has no impact while seeing the code. 

I checked that the variables are indeed set by doing `C-h v` (describe variable) and checking that they are indeed `t`.

(BTW I really like your YT videos on emacs! Thanks for all the hard work on them!)

**Comment by sidkshatriya** [comment]
I'm using emacs-29 (29.0.50) with version 2.0.0 of modus themes.

**Comment by protesilaos** [comment]
> I added the setq for bold constructions and italic constructs but for some reason it has no impact while seeing the code.

Ah yes, I forgot to note that you need to reload the theme for changes to take effect (it is documented in the manual).  This is true every time you set a customisation optionsto a new value.

> (BTW I really like your YT videos on emacs! Thanks for all the hard work on them!)

You are welcome!

**Comment by sidkshatriya** [comment]
Actually I was restarting my emacs and that was still not helping. 

I had added `modus-operandi` to my `~./spacemacs` file:

```elisp
   ;; List of themes, the first of the list is loaded when spacemacs starts.
   ;; Press `SPC T n' to cycle to the next theme in the list (works great
   ;; with 2 themes variants, one dark and one light)
   dotspacemacs-themes '(modus-operandi
                         spacemacs-light
                         spacemacs-dark)
```

But this does not help. However, adding an explicit `(load-theme modus-operandi)` does the trick for bold/italic constructs.

The operandi theme is beautiful! Thanks!

**Comment by protesilaos** [comment]
Good to know.  Thank you!
