### ISSUE TITLE
modus-themes--slant overspecifies slant attribute

### ISSUE THREAD

**Issue by derek-upham** [protesilaos/modus-themes#21]
The `modus-themes-slant` definition is the following ([ref](https://github.com/protesilaos/modus-themes/blob/main/modus-themes.el#L4185)):

```
`(modus-themes-slant ((,class :inherit italic :slant ,@(modus-themes--slant))))
```

The `modus-themes--slant` function has this definition ([ref](https://github.com/protesilaos/modus-themes/blob/main/modus-themes.el#L2945-L2949)):

```
(defun modus-themes--slant ()
  "Conditional use of italics for slant attribute."
  (if modus-themes-italic-constructs
      (list 'italic)
    (list 'normal)))
```

The function controls the face display by overriding the parent's slant with `italic` or `normal`.

This breaks if the user has configured the `italic` face to use oblique glyphs:

```
(set-face-attribute 'italic nil :slant 'oblique)
```

In that case the theme overrides the parent to be italic again, and the oblique glyphs never appear.  (This is relevant for the Iosevka font family, which has italic and oblique variants.)

If the function used `unspecified` in place of `italic`, things ought to work as expected for all cases.

```
(defun modus-themes--slant ()
  "Conditional use of italics for slant attribute."
  (if modus-themes-italic-constructs
      (list 'unspecified)
    (list 'normal)))
```

**Comment by protesilaos** [comment]
Hello @derek-upham and thanks for reporting this!

What do you think about this instead?

```diff
 modus-themes.el | 9 ++++-----
 1 file changed, 4 insertions(+), 5 deletions(-)

diff --git a/modus-themes.el b/modus-themes.el
index a3bf7c3..92f8498 100644
--- a/modus-themes.el
+++ b/modus-themes.el
@@ -2944,9 +2944,8 @@ (defun modus-themes--bold-weight ()
 
 (defun modus-themes--slant ()
   "Conditional use of italics for slant attribute."
-  (if modus-themes-italic-constructs
-      (list 'italic)
-    (list 'normal)))
+  (when modus-themes-italic-constructs
+    (list :inherit 'italic)))
 
 (defun modus-themes--fixed-pitch ()
   "Conditional application of `fixed-pitch' inheritance."
@@ -4182,7 +4181,7 @@ ;;;;; other custom faces
     `(modus-themes-search-success-modeline ((,class :foreground ,@(modus-themes--deuteran
                                                                    blue-active
                                                                    green-active))))
-    `(modus-themes-slant ((,class :inherit italic :slant ,@(modus-themes--slant))))
+    `(modus-themes-slant ((,class ,@(modus-themes--slant))))
     `(modus-themes-ui-variable-pitch ((,class ,@(modus-themes--variable-pitch-ui))))
     `(modus-themes-fixed-pitch ((,class ,@(modus-themes--fixed-pitch))))
     `(modus-themes-markup-code
```

It makes it the same as `modus-themes-bold` face with how it uses the `modus-themes--bold-weight` function.

**Comment by derek-upham** [comment]
I see that it's also consistent with `modus-themes--fixed-pitch` and `modus-themes--variable-pitch-ui`, so it's a well-tested solution.  Let's use that.  Thank you.

**Comment by protesilaos** [comment]
Just pushed the changes.  Thanks again for your feedback!
