### ISSUE TITLE
Changing from operandi to vivendi has effect on agenda

### ISSUE THREAD

**Issue by mfuchs1** [protesilaos/modus-themes#27]
When I change from operandi to vivendi theme there's a strange effect on my agenda:

I use org-gcal to sync my org-agenda with my google calendar.

So when I use operandi theme and I open my agenda, everything is fine and my google events are displayed.

But when I change to the dark theme (vivendi) via F5 and I re-open my agenda, it won't display my org-gcal events - but only the agenda events from my "local" org-files.

P.S.: And a big "Thank You!" for all your precious work - I just love your Videos and your themes are the best - the only themes I use.

**Comment by mfuchs1** [comment]
P.S.: And a big "Thank You!" for all your precious work - I just love your Videos and your themes are the best - the only themes I use.

**Comment by protesilaos** [comment]
Hello @mfuchs1!

> When I change from operandi to vivendi theme there's a strange effect on
> my agenda:
> 
> I use org-gcal to sync my org-agenda with my google calendar.
> 
> So when I use operandi theme and I open my agenda, everything is fine
> and my google events are displayed.
> 
> But when I change to the dark theme (vivendi) via F5 and I re-open my
> agenda, it won't display my org-gcal events - but only the agenda events
> from my "local" org-files.

This is strange.  I took a quick look at org-gcal.el in hope of finding
a faulty face, but there are none.

Given that I don't use that package of google calendar, how can I
reproduce this issue.  Perhaps you can share with me screenshots and
relevant customisations you have made?

> P.S.: And a big "Thank You!" for all your precious work - I just love
> your Videos and your themes are the best - the only themes I use.

You are welcome!  I appreciate your kind words.

**Comment by mfuchs1** [comment]
Hello protesilaos,

Thanks for your fast reply.

I can give you two screenshots: the first one shows my full agenda with modus-operandi. Then I closed the agenda, changed to modus-vivendi with a keybinding (f5) and made the second screenshot.

Here are the relevant customisations of the modus-themes:

```
(use-package modus-themes
  :ensure
  :init
  ;; Add all your customizations prior to loading the themes
  (setq modus-themes-italic-constructs t
        modus-themes-bold-constructs nil
        modus-themes-region '(bg-only no-extend))

  ;; Load the theme files before enabling a theme
  (modus-themes-load-themes)
  :config
  ;; Load the theme of your choice:
  (modus-themes-load-operandi) ;; OR (modus-themes-load-vivendi)
  :bind ("<f5>" . modus-themes-toggle))

```

... and from org-gcal:

```
(use-package org-gcal
    :ensure t
    :after org
    :config
    (setq org-gcal-client-id "XXX.apps.googleusercontent.com"
          org-gcal-client-secret "XXX"
          org-gcal-file-alist '(("matthiasfuchs01@gmail.com" .  "/home/matthias/RoamNotes/org-gcal.org")
		      ("60987qvicve83spd52ims9417c@group.calendar.google.com" .  "/home/matthias/RoamNotes/golling.org")
		      ("s6qc6o2pg9aageq3s4ekkcgtd0@group.calendar.google.com" .  "/home/matthias/RoamNotes/parsch.org"))))

(add-hook 'org-agenda-mode-hook (lambda () (org-gcal-sync) ))
;; Ich habe die nächste Zeile auskommentiert; vielleicht vermeide ich somit doppelte Einträge in der org-agenda mit capture.
(add-hook 'org-capture-after-finalize-hook (lambda () (org-gcal-sync) ))
```
![Screenshot_20220406_195933](https://user-images.githubusercontent.com/24796328/162044984-c6973793-25f0-4aee-943f-5d3578e543ea.png)
![Screenshot_20220406_200020](https://user-images.githubusercontent.com/24796328/162044991-dc651224-b077-435b-8599-8a6b2908e664.png)

**Comment by mfuchs1** [comment]
I've tried your solution with different themes and it worked - the agenda is in the desired state. Thank you! :-)

**Comment by mfuchs1** [comment]
So the problem isn't limited to theme switching - the problem were the missing files in the org-agenda-files.

**Comment by protesilaos** [comment]
Very well!  I am thus closing this issue.

Here is how I set up the agenda files in my dotemacs by giving it a list of strings as file paths:

```elisp
(setq org-agenda-files `(,org-directory "~/Documents"))
```

And the `org-directory` expands to:

```elisp
(setq org-directory (convert-standard-filename "~/Documents/org"))
```

This way, any Org file in either the `~/Documents` or `~/Documents/org` gets included.  Of course you can add more refined file paths if you need them.
