### ISSUE TITLE
Invalid face attribute while using centaur-tabs

### ISSUE THREAD

**Issue by CsBigDataHub** [protesilaos/modus-themes#30]
Hi @protesilaos ,
I am not sure if you are still active in github. 

I am reporting a bug here until figure out how to report one on `SourceHut`.

My `*Messages*` buffer is flooded with error when using `centaur-tabs` below -
```
Invalid face attribute :foreground nil
Invalid face attribute :background nil [5 times]
```

Theme used - `modus-vivendi`

I am not sure where this bug needs to be fixed, so I opened a issue in `centaur-tabs` repo as well.

https://github.com/ema2159/centaur-tabs/issues/187

probably this issue similar to the issue below - https://github.com/ema2159/centaur-tabs/issues/102

**Comment by protesilaos** [comment]
Hello @CsBigDataHub!

It is a bug in the `centaur-tabs`.  I sent a PR some months ago: https://github.com/ema2159/centaur-tabs/pull/179.  Maybe you want to mention it in your issue.

**Comment by CsBigDataHub** [comment]
Thanks @protesilaos,

Tested your PR, `Invalid face attribute :background nil` has disappeared. 

Still seeing `Invalid face attribute :foreground nil`


```
evil-line-move: Buffer is read-only: #<buffer *Messages*>Invalid face attribute :foreground nil
Invalid face attribute :foreground nil [5 times]
evil-line-move: Buffer is read-only: #<buffer *Messages*>Invalid face attribute :foreground nil
Invalid face attribute :foreground nil [23 times]
evil-line-move: Buffer is read-only: #<buffer *Messages*>Invalid face attribute :foreground nil
Invalid face attribute :foreground nil [35 times]
```

**Comment by protesilaos** [comment]
My email didn't reach this issue... GitHub seems to have this problem.  Copying below.

* * *
> Tested your PR, `Invalid face attribute :background nil` has disappeared. 

Very well!

> Still seeing `Invalid face attribute :foreground nil`
> ```
> evil-line-move: Buffer is read-only: #<buffer *Messages*>Invalid face attribute :foreground nil
> Invalid face attribute :foreground nil [5 times]
> evil-line-move: Buffer is read-only: #<buffer *Messages*>Invalid face attribute :foreground nil
> Invalid face attribute :foreground nil [23 times]
> evil-line-move: Buffer is read-only: #<buffer *Messages*>Invalid face attribute :foreground nil
> Invalid face attribute :foreground nil [35 times]
> ```

We need to track the source of 'evil-line-mode'.  It probably is the
same issue where it expects an explicit :foreground attribute and thus
does not work without one.

**Comment by CsBigDataHub** [comment]
@protesilaos This is just me pressing `<down arrow>` on `*Messages*` buffer(read-only buffer) , which flashes `warning bell` and `Invalid face attribute :foreground nil` will appear.

**Comment by CsBigDataHub** [comment]
Is there a way to find what is casing this message? `toggle-debug-on-error` would not trigger any errors when this message appears.

**Comment by protesilaos** [comment]
I am not sure how to debug this.  Does it only happen with the down arrow?  If yes, then we need to find which command is called by that key (`M-x describe-key` or `C-h k` and then down arrow) and continue searching from there.

**Comment by CsBigDataHub** [comment]
Thanks again @protesilaos ,

Found the culprit. Setting both options causes this error. 

```
(setq centaur-tabs-set-icons t)
(setq centaur-tabs-plain-icons t)
```

Just setting one option fixed it. Went with `(setq centaur-tabs-set-icons t)`.

Your PR worked just fine.

**Comment by protesilaos** [comment]
@CsBigDataHub The `centaur-tabs` maintainer has merged my patch: https://github.com/ema2159/centaur-tabs/pull/179

I will reinstate support for the package at the theme level.

**Comment by CsBigDataHub** [comment]
Thanks @protesilaos

**Comment by protesilaos** [comment]
You are welcome!

**Comment by protesilaos** [comment]
> Tested your PR, `Invalid face attribute :background nil` has disappeared. 

Very well!

> Still seeing `Invalid face attribute :foreground nil`
>
>
> ```
> evil-line-move: Buffer is read-only: #<buffer *Messages*>Invalid face attribute :foreground nil
> Invalid face attribute :foreground nil [5 times]
> evil-line-move: Buffer is read-only: #<buffer *Messages*>Invalid face attribute :foreground nil
> Invalid face attribute :foreground nil [23 times]
> evil-line-move: Buffer is read-only: #<buffer *Messages*>Invalid face attribute :foreground nil
> Invalid face attribute :foreground nil [35 times]
> ```

We need to track the source of 'evil-line-mode'.  It probably is the
same issue where it expects an explicit :foreground attribute and thus
does not work without one.

-- 
Protesilaos Stavrou
https://protesilaos.com
