### ISSUE TITLE
Cosmetic issue in manual when using `info+`

### ISSUE THREAD

**Issue by joncol** [protesilaos/modus-themes#33]
Hi, thanks for the great themes.

Just a heads up: I'm using the `info+` package, via the `straight`/`use-package` incantation:

```elisp
  (use-package info+
  :straight (info-plus :type git :host github :repo "emacsmirror/info-plus")
  :after info)
```

This results in the following colors when viewing the info pages for the Modus themes:
![quotes](https://user-images.githubusercontent.com/194062/173510231-ce5f3876-7395-45ee-8769-ef518bea92c9.png)

As can be seen, the quotes are colored in a pretty ugly way, since the opening quotes are backticks and the closing quotes are apostrophes.

If you can think of a simple solution to this (except for disabling `info+` :smile:), it would be nice...

**Comment by protesilaos** [comment]
Hello @joncol!

This is because (i) we do not currently support `info+` and (ii) it defines its own faces.

I will see to it and report back to you.

**Comment by protesilaos** [comment]
Hello again!  Just pushed the changes.  Please take a look and let me know what you think.  We can still refine things.

```
  commit e342e3568c8a3a1cc20714c774bbe9df68489b32
  Author: Protesilaos Stavrou <info@protesilaos.com>
  Date:   Tue Jun 14 10:23:44 2022 +0300
  
      Add support for info+
      
      As is the case with PACKAGE+ packages from the Emacs Wiki, info+ defines
      lots of faces that hardcode colour values instead of inheriting from
      basic faces.  It does so for no good reason.  Furthermore, these faces
      colourise too much, making the buffer harder to read.
      
      Some of the changes I introduce here outright remove colouration, while
      others align the various constructs with the overall aesthetic of the
      themes.
      
      Note that, by default, info+ adds clickable buttons to glossary terms.
      This produces awkward combinations such as by buttonising the "string"
      component inside of what actually is a function's argument.  So you
      have, say, FORMAT-[STRING] where "[]" represents the button: the FORMAT
      gets one face and the [STRING] another, even though they are part of a
      single argument.  To me this looks broken and is counter-productive,
      though it is not up to the theme to decide how packages fontify the
      various constructs.  At any rate, button styles at the theme level are
      controlled by the user option 'modus-themes-box-buttons'.
      
      Thanks to Jonas Collberg for the feedback in issue 33 over at the GitHub
      mirror: <https://github.com/protesilaos/modus-themes/issues/33>.
```

**Comment by joncol** [comment]
Thanks for the quick fix! It looks great now.

**Comment by protesilaos** [comment]
You're welcome!

**Comment by joncol** [comment]
One small detail:
![links](https://user-images.githubusercontent.com/194062/173534758-faa985e8-625c-4f92-ae73-ea81c52994b1.png)

Some of the words are turned into links. In the example image you can see this happening for the words `list`, `text`, and `point`. It seems they link to the Emacs glossary. I don't know if there's an easy fix for that as well?

**Comment by protesilaos** [comment]
I mentioned this in the commit message.  Basically, it is outside our control.  Looking at `info+.el` (with `M-x find-library`), there is a user option `Info-fontify-glossary-words`. Its docstring explains the technicalities.  This seems to disable those buttons altogether:

```elisp
(setq Info-fontify-glossary-words nil)
```

**Comment by joncol** [comment]
Oh, completely missed that. Thanks for the clarification.

**Comment by protesilaos** [comment]
That's okay.
