### ISSUE TITLE
Increase high contrast for some commands

### ISSUE THREAD

**Issue by iris-garcia** [protesilaos/modus-themes#34]
Hi Protesilaos, I've been using modus-themes for more than a year now and I love both of them.
Quite often I find myself struggling to find out in which occurence I am when for example, doing a search in the buffer (consul-line), as shown in the screenshot.

![image](https://user-images.githubusercontent.com/3024945/174970481-5193d4cb-d7e7-4cc7-a4d4-784ef75151c4.png)

In the interest of having a high contrast and in my opinion a quicker way of finding the selected line in these situations I wonder if it would be possible to underline the current line. And of course, if you think there is another possible change with colors (like giving a shadow to the selected line) I'm all ears.

Thank you.

**Comment by protesilaos** [comment]
Hello @iris-garcia!

> like giving a shadow to the selected line

This is done by default, but because your background is already gray it is invisible.

Anyhow, there is the user option `modus-themes-completions`.  Here is an example:

```elisp
;; The `modus-themes-completions' is an alist that reads three keys:
;; `matches', `selection', `popup'.  Each accepts a nil value (or empty
;; list) or a list of properties that can include any of the following
;; (for WEIGHT read further below):
;;
;; `matches' - `background', `intense', `underline', `italic', WEIGHT
;; `selection' - `accented', `intense', `underline', `italic', `text-also', WEIGHT
;; `popup' - same as `selected'
;; `t' - applies to any key not explicitly referenced (check docs)
;;
;; WEIGHT is a symbol such as `semibold', `light', or anything
;; covered in `modus-themes-weights'.  Bold is used in the absence
;; of an explicit WEIGHT.
(setq modus-themes-completions
      '((matches . (extrabold))
        (selection . (semibold intense)) ; add `accented' to the list for a colourful background
        (popup . (extrabold))))
```

**Comment by iris-garcia** [comment]
Oh wow, this is my fault. I have not check for the latest updates (I didn't even have the modus-themes-completions variable set).

Thank you and sorry!
