### ISSUE TITLE
Can't get the same look in doom-emacs for the operandi theme

### ISSUE THREAD

**Issue by wd** [protesilaos/modus-themes#35]
From the screenshot here https://protesilaos.com/emacs/modus-themes-pictures
![image](https://user-images.githubusercontent.com/58177/175184324-53b14ca5-12d9-4136-85b9-58efa1afdbc5.png)

I can see the background of minibuffer is white.

But it looks a little bit darker when I use this theme in doom-emacs. I have tried many ways to find out where I can set the background color for the minibuffer but failed. The only thing I found is I can set the background for `modus-themes-completion-selected`, but I don't want to do that, since I think this is not a problem for modus. 

This is the output of M-x with vertico enabled.

<img width="660" alt="image" src="https://user-images.githubusercontent.com/58177/175184411-956ca9b2-b277-4bc0-a12c-7744168b25db.png">

any help is appreciated.

**Comment by protesilaos** [comment]
Hi @wd! This is most likely due to Solaire: https://github.com/hlissner/emacs-solaire-mode

Try to disable the `solaire-mode`.

**Comment by wd** [comment]
> Hi @wd! This is most likely due to Solaire: https://github.com/hlissner/emacs-solaire-mode
> 
> Try to disable the `solaire-mode`.

Oh, my lord, I just discovered this from doomemacs repo and go back to this issue to post the solution, and found that you already give me the solution 40 min ago...

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/58177/175199005-a2f935ea-864e-41cb-81ff-9f6644171d9e.png">

**Comment by protesilaos** [comment]
Very well!  I think I should mention Solaire in the README as it will probably surprise a lot of people.
