### ISSUE TITLE
svg get incorrectly rendered in color

### ISSUE THREAD

**Issue by wang1zhen** [protesilaos/modus-themes#36]
Hi,

I have been experiencing weird rendering issues when svg files get rendered in emacs.

Here is the svg file generated by xenops package which is correctly rendered in edge:

![image](https://user-images.githubusercontent.com/31798841/180019019-3516e0d7-4f7b-432d-9391-db7d750c008e.png)
 
However, in emacs, the colors get weird:
 
![image](https://user-images.githubusercontent.com/31798841/180019055-a0f7961d-8336-40e2-83db-6ead49f95050.png)

When I switch to another theme (i.e. tango-dark), these kind of issue is gone:
 
![image](https://user-images.githubusercontent.com/31798841/180019087-9118b784-c389-40e4-abaa-610c0dbf99eb.png)

Would you please help to figure out the reason for that? Currently I have totally no clue.

The svg file which I used for test is attached below:

![e2a0a696c9367dcb26c08036e113c96d2830ce36](https://user-images.githubusercontent.com/31798841/180019384-c8a08b66-78a0-4ecf-955d-ac6c4203965e.svg)

**Comment by protesilaos** [comment]
Hello @wang1zhen!

> Would you please help to figure out the reason for that? Currently I have totally no clue.

I can help but I need instructions on how to reproduce this.  I don't use latex myself.

To find information about a character you see, place the point (cursor) over it and do `M-x describe-char` (by default it is bound to `C-u C-x =`).  It will produce a Help buffer.  Towards the bottom of that buffer there is information about the face that is used, if any.  Or you can just copy the whole Help buffer here for me to check.

**Comment by protesilaos** [comment]
This is strange.  Your Help buffer shows these:

```
(font-lock-keyword-face font-latex-sedate-face)
```

None of them has a background colour, so I am not sure where that is coming from.  I also notice [in this demo](https://user-images.githubusercontent.com/31798841/180060714-099f1140-18a9-41ee-bb42-306741d4870c.png) that one equation is cyan and another is violet.

Do you have a way for me to reproduce this?  Maybe some sample file I can use and the packages I need to install?

**Comment by wang1zhen** [comment]
And here's my steps to reproduce.
1. have latex installed (`sudo apt install texlive-full -y`)
2. clone the repository https://github.com/jwiegley/use-package to `~/test/`
3. save the following test latex document as `~/test/test.tex`
```
\documentclass{article}
\usepackage{amsmath}
\begin{document}
An example equation is
\begin{equation*}
\frac{\partial \mathcal{L}}{\partial q} - \frac{d}{dt}\frac{\partial \mathcal{L}}{\partial \dot{q}} = 0.
\end{equation*}
The document continues.
\end{document}
```
4. `emacs -Q`
5. eval the following block
```
(add-to-list 'load-path "~/test/use-package")
(require 'use-package)

(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)

(use-package modus-themes
  :ensure t)

(use-package xenops
  :ensure t)

(load-theme 'modus-vivendi t)
```
6. `C-x C-f` visit the test.tex file
7. `M-x xenops-mode` (need to execute twice)
8. here it goes
![image](https://user-images.githubusercontent.com/31798841/180067252-4b83d168-ced1-4092-a89b-fab2afa19d47.png)

I feel sorry for the overlong reproduce steps and you might need to install texlive-full which is several GB large. There might be some better methods to reproduce it yet this is closest one to my configs

**Comment by protesilaos** [comment]
> There might be some better methods to reproduce it yet this is closest one to my configs

Thanks!  I will try it tomorrow first thing in the morning.  Local time is close to 23h and I have been awake since ~5.  Will update you on my progress.

**Comment by protesilaos** [comment]
Using this (`use-package` is not relevant here):

```elisp
(package-initialize)

(require 'modus-themes)
(require 'xenops)

;; It works with the light theme
(load-theme 'modus-operandi t)

;; (load-theme 'modus-vivendi t)

(find-file "~/test-files/test.tex")

;; Then invoke `xenops-mode' twice
```

I am able to reproduce the problem with `modus-vivendi` but not with `modus-operandi`.  Screenshot of the latter:

![Screenshot from 2022-07-21 08-57-26](https://user-images.githubusercontent.com/12828033/180140934-964e468d-a8c1-480d-950f-676a1c33a4f5.png)

This leads me to believe that `xenops` is doing something behind the scenes which does not work with a purely black background.

To confirm this hypothesis, tweak the sample code:

```elisp
(package-initialize)

(require 'modus-themes)
(require 'xenops)

;; It works with the light theme
;; (load-theme 'modus-operandi t)

(load-theme 'modus-vivendi t)

;; Change the background to test if it behaves properly
(set-face-attribute 'default nil :background "gray30")

;; Make it black again
(set-face-attribute 'default nil :background "black")

(find-file "~/test-files/test.tex")

;; Then invoke `xenops-mode' twice
```

Check the results:

![Screenshot from 2022-07-21 09-02-26](https://user-images.githubusercontent.com/12828033/180140973-b06a9d2e-beaf-4aea-8274-6aa3eb38abce.png)

![Screenshot from 2022-07-21 09-03-01](https://user-images.githubusercontent.com/12828033/180140974-69e11ab3-2490-455f-b338-2cc879176538.png)

The bug is in the `xenops` package.  It seems to assume that black is an inappropriate background, presumably because the text of the equation would also be black, so it decides to use another colour (likely by applying `:inverse-video`).  I am not familiar with the code, but a check for `color-dark-p` seems more appropriate.

**Comment by wang1zhen** [comment]
Thanks prot! Now I can confirm that iff the background color of default face exactly matches "black", the formulae would be rendered incorrectly. I shall report this to xenops package and try to fix it. Again, thanks for your time.

**Comment by protesilaos** [comment]
You are welcome!  If you want, we can keep this issue open until xenops changes things.  Though I don't mind you closeed it.
