### ISSUE TITLE
white line over modeline

### ISSUE THREAD

**Issue by laampui** [protesilaos/modus-themes#37]
Thank you for your effort for this great package. Recently I found an issue while using with `keycast`. There is one pixel line through the background. 
![Screenshot_20220723_082952](https://user-images.githubusercontent.com/15785343/180583414-04b352e8-fbad-4bde-9280-220211a66cce.png)

I 've reproduce this in `emacs -Q` with the following code snippet
```elisp
(use-package modus-themes
  ;; (info "(modus-themes) Top")
  :init
  (setq modus-themes-mode-line '(moody accented borderless))
  (modus-themes-load-themes)
  :config
  ;; Load the theme of your choice:
  (modus-themes-load-operandi)
  :bind ("<f5>" . modus-themes-toggle))

(use-package keycast
  :init
  (with-eval-after-load 'keycast
    (define-minor-mode keycast-mode
      "Show current command and its key binding in the mode line."
      :global t
      (if keycast-mode
          (add-hook 'pre-command-hook 'keycast--update t)
        (remove-hook 'pre-command-hook 'keycast--update)))

    (add-to-list 'global-mode-string '("" keycast-mode-line " ")))
  (keycast-mode))
```

**Comment by laampui** [comment]
After reading the docs, I should remove the `moody` to get what i want.

**Comment by protesilaos** [comment]
Hello @laampui!  Glad you found it.  If there is still a problem, please let me know.
