### ISSUE TITLE
Inverted themes

### ISSUE THREAD

**Issue by Andre0991** [protesilaos/modus-themes#38]
Hi, Prot!

I guess this request/question is a bit weird, but here we go :D

I read PDFs in Emacs and it's usual for these files to have a white background. Reading them at night is uncomfortable, so I usually invert colours on my operating system. That literally invert all colours in all applications. This way, the PDFs get way easier to read.

However, as a side effect, the Modus themes colours get different, of course. The result is not terrible, it's usable, but it's jarring since I'm used to the original themes.

So, I'm wondering if there's an easy way of inverting all colours definitions from a modus themes. That would make it look like the original theme again.

Any pointers in this direction? I suppose I'd need to copy the Modus themes and manually invert all of its colours definitions. Maybe there's an easier way...?

**Comment by protesilaos** [comment]
Hello @Andre0991!

What package do you use to view PDFs in Emacs?  Have you tried `pdf-tools`?  It has a "night mode" which should work perfectly fine for your case.

I can help with whatever technicalities.

**Comment by Andre0991** [comment]
Oh, you're right, there's `pdf-view-midnight-minor-mode`. Great.

I missed it because I was trying to use`pdf-view-dark-minor-mode`, which is not the same thing.

Thanks, and sorry for the noise :)

**Comment by protesilaos** [comment]
You are welcome!
