### ISSUE TITLE
background color makes the texts visually unclear

### ISSUE THREAD

**Issue by fu123456** [protesilaos/modus-themes#4]
![module_theme_issue](https://user-images.githubusercontent.com/22411577/126524359-81c0eeaf-b279-481e-8339-e2d08655158e.png)

**Comment by fu123456** [comment]
In many times, I cannot see the text under the background color clearly. So I want to know how to change the background color or its transparency to make the text clear. Very thanks.

**Comment by protesilaos** [comment]
Hello @fu123456 and thanks for reporting this!  What are you using to produce those highlights?  That looks like a shell prompt and it seems to list directories.  But what is that green background?

Please place the point over the green background and do `M-x describe-char` (`C-u C-x =`) and send me the contents of Help buffer you get from that.

**Comment by fu123456** [comment]
In Vterm. Note eshell seems to be OK.

**Comment by fu123456** [comment]
I execute "M-x describe-char". My emacs output:
             position: 63989 of 63989 (100%), column: 26
            character: C-j (displayed as C-j) (codepoint 10, #o12, #xa)
              charset: ascii (ASCII (ISO646 IRV))
code point in charset: 0x0A
               script: latin
               syntax:   	which means: whitespace
             to input: type "C-x 8 RET a" or "C-x 8 RET LINE FEED (LF)"
          buffer code: #x0A
            file code: #x0A (encoded by coding system utf-8-unix)
              display: no font available

Character code properties: customize what to show
  old-name: LINE FEED (LF)
  general-category: Cc (Other, Control)

There are text properties here:
  font-lock-face       (:foreground "#ffffff" :background "#000000" :weight normal :underline nil :slant normal :inverse-video nil :strike-through nil)

**Comment by fu123456** [comment]
![my_issue](https://user-images.githubusercontent.com/22411577/126526875-7bd60b3e-7953-4750-89b1-655adcd55d6a.png)

**Comment by protesilaos** [comment]
This looks like an underlying shell/vterm issue as there are no faces here for us to customise.  But we must be sure about it.

Do you notice this only for directories with 777 permissions?  And what shell do you use?  It does not happen on my end with Bash:

![Screenshot from 2021-07-21 19-51-53](https://user-images.githubusercontent.com/12828033/126528525-79dea4bc-0565-4bbd-8cf6-c87709deed38.png)

**Comment by protesilaos** [comment]
Also note that you need to put the point over the green background.  Maybe you have to use the mouse for that.  And then try `M-x describe-char`.

**Comment by fu123456** [comment]
This seems to be only with 777 permissions. In terminal, I use zsh (not bash). So the vterm uses the zsh.

**Comment by fu123456** [comment]
I should do according to your steps. I use the mouse to put the point on the green region, then M-x describe-char.

**Comment by fu123456** [comment]
Eshell does work well. It only has issue in Vterm.

**Comment by protesilaos** [comment]
How about in `M-x shell` which should run zsh under the hood.

**Comment by fu123456** [comment]
![issue1](https://user-images.githubusercontent.com/22411577/126533868-103ad78b-25bd-42e4-a107-999a1b2798a3.png)

**Comment by fu123456** [comment]
![issue2](https://user-images.githubusercontent.com/22411577/126534053-53f3e21e-3cda-4e31-96ce-d2559e984a6d.png)

**Comment by protesilaos** [comment]
Thanks!  This looks like a zsh issue then.  It does not happen in Eshell because it uses its own elisp interpreter.

If you do this in a terminal emulator, do you get those 777 directories with a green background and a blue text?

**Comment by protesilaos** [comment]
Unless you have a shell alias... I am not sure how to check those in zsh, but on Bash this should show the alias:

```
alias ls
```

**Comment by fu123456** [comment]
![issue3](https://user-images.githubusercontent.com/22411577/126539845-e1db91a7-3591-448e-bccf-e1a4ced9d65c.png)

**Comment by fu123456** [comment]
I use "/usr/bin/ls -la", which can remove all colors. But in some situations, we also hope some colors for me.

**Comment by protesilaos** [comment]
I can't reproduce this on my end. I am trying zsh with xfce4-terminal. I also used several of the built-in palettes, none of which shows a problem.  For example:

![Screenshot from 2021-07-21 21-46-20](https://user-images.githubusercontent.com/12828033/126543171-896001af-2d2e-4bf5-971a-808c751c0eda.png)

This has to be an issue with your zsh configuration or with the dircolors

**Comment by protesilaos** [comment]
Hello again @fu123456!  Have you had the chance to investigate the bug with `ls -la --color=auto` and zsh?  We were at the point where you could reproduce the bug on your Urxvt terminal emulator, suggesting that this is not a problem with the `modus-themes` or with Emacs in general.
