### ISSUE TITLE
Which Emacs are the themes compatible with?

### ISSUE THREAD

**Issue by rpgoldman** [protesilaos/modus-themes#40]
I was trying to install this into Aquamacs (a mac-specific Emacs port), which is lagging (it's based on GNU Emacs 25.3.50.1). Should I be able to load the modus-themes? I tried, but modus-themes uses `if-let*`, which isn't in the `subr-x.el` I have.

**Comment by protesilaos** [comment]
Hi @rpgoldman!  The themes require at minimum Emacs 27.1.  I am only using GNU Emacs though, so I do not know about other variants.

**Comment by rpgoldman** [comment]
Thank you @protesilaos ! I will wait for the version that moves to Emacs 28 then, thanks!

**Comment by protesilaos** [comment]
You are welcome!
