### ISSUE TITLE
Visually inconsistencies within org chunks

### ISSUE THREAD

**Issue by cddesja** [protesilaos/modus-themes#43]
Not sure if this is a modus-themes bug or not, but if you see the screenshot below you'll notice lots of visual inconsistencies (e.g., <- is different in two places, sometimes a ) and a > has a background color other times it doesn't).  

<img width="1065" alt="image" src="https://user-images.githubusercontent.com/1608939/191740629-755acfc7-d1ed-43ae-b201-27f931c33ff8.png">

The visual inconsistencies disappear when viewed in ESS mode.

<img width="837" alt="image" src="https://user-images.githubusercontent.com/1608939/191740887-9483718a-76f0-4c76-86db-ddbd8a130a75.png">

Any thoughts about how to fix this? Thanks for the amazing theme, too.

**Comment by protesilaos** [comment]
Hello @cddesja!  Can you place the point over a character that has an inconsistent style and type `M-x describe-char` (or `C-u C-x =`)?  It will produce a Help buffer.  Can you copy the contents of that buffer?

It is unlikely that the themes are at fault here, as they do not control which faces are applied.  But we will find out more.

**Comment by cddesja** [comment]
Thanks for the quick reply! It looks the problem is the rainbow-delimiters and not the modus-theme. Thanks for suggesting to use `M-x describe-char`. This can be closed.

**Comment by protesilaos** [comment]
You are welcome!
