### ISSUE TITLE
New Update 

### ISSUE THREAD

**Issue by mfuchs1** [protesilaos/modus-themes#44]
With the new update of the modus themes Emacs asks at every start: Loading a theme can run Lisp code. Really load? 

In the message buffer this issue: "Setting ‘custom-safe-themes’ temporarily since "emacs -q" would overwrite customizations".

How can I fix this? I've installed the themes via melpa....

Thanks a lot.

**Comment by mfuchs1** [comment]
Update: I've found the source of this issue: this line in my init.el "'(custom-enabled-themes '(modus-vivendi))" caused the issue. I've deleted it and everything is okay now.

Dear protesilaos - your themes are the best. Mostly I use modus-vivendi / operandi, bur I do like ef-bio and ef-autumn a lot, too.

And I want to share something about your videos about philosophy: 13 years of my life I spent in a catholic monastery. Yes, I was a monk. So during this time I studied (and I'm still studying) philosophy - our great teachers were the "old" greek philosophers. The starting point of our philosophy are the great human experiences like art, friendship, ... 

I love your videos about philosophy - they help me a lot... Thank you! Have a great day...

**Comment by protesilaos** [comment]
Hello @mfuchs1!

> Update: I've found the source of this issue: this line in my init.el "'(custom-enabled-themes '(modus-vivendi))" caused the issue. I've deleted it and everything is okay now.

Very well!  What did you do in the end?  Just asking in case someone else has the same issue.

I normally use `load-theme` with the `NO-CONFIRM` argument set to non-nil, like:

```elisp
(load-theme 'modus-vivendi t)
```

Or, easier to read:

```elisp
(load-theme 'modus-vivendi :no-confirm)
```

> Dear protesilaos - your themes are the best. Mostly I use modus-vivendi / operandi, bur I do like ef-bio and ef-autumn a lot, too.

Thank you!  I created the `ef-themes` because people would ask me for stylistic alternatives to the `modus-themes`.  Basically, something more colourful but "okay" in terms of legibility.

> And I want to share something about your videos about philosophy: 13 years of my life I spent in a catholic monastery. Yes, I was a monk. So during this time I studied (and I'm still studying) philosophy - our great teachers were the "old" greek philosophers. The starting point of our philosophy are the great human experiences like art, friendship, ...

Good to know!  If you ever feel like telling me more about your experience, please do it.  Though better use my email: <https://protesilaos.com/contact>.

> I love your videos about philosophy - they help me a lot... Thank you! Have a great day...

Thank you!  Have a nice day as well!

* * *

I am closing this issue since you fixed it.

**Comment by mfuchs1** [comment]
Hello @protesilaos,
the configuration of the modus-themes in my init.el is like this

`(use-package modus-themes
  :ensure
  :init
  ;; Add all your customizations prior to loading the themes
  (setq modus-themes-italic-constructs t
        modus-themes-bold-constructs nil
        modus-themes-region '(bg-only no-extend))

  ;; Load the theme files before enabling a theme
  (modus-themes-load-themes)
  :config
  ;; Load the theme of your choice:
  (modus-themes-load-operandi) ;; OR (modus-themes-load-vivendi)
  :bind ("<f5>" . modus-themes-toggle))`

With the last update of the modus-themes Emacs asked at every start-up: "Loading a theme can run Lisp code. Really load?". I tried to load another theme - the same issue. So I looked closely at my init.el and found this line: `'(custom-enabled-themes '(modus-vivendi))`

I really don't know how this line `'(custom-enabled-themes '(modus-vivendi))` ended up in my init.el. I deleted this line - and this issue was "gone", I was able to load my theme and any other theme. Yes, normally I use the same code to load a theme as you do. But with the modus-themes I took your example of configuration. 

I hope my answer is helpful. 
Have a great and blessed day.

Yes I will contact you and tell you about my experience. Thank your for your great work! I'm learning a lot from you and your videos.

**Comment by protesilaos** [comment]
Thank you for the explanation!  I am not sure how that `custom-enabled-themes` ended up in your init file.  Maybe you used some Custom UI interface at some point.  At any rate, I am happy this is solved.  Getting prompted the whole time is annoying.

Looking forward to your email!
