### ISSUE TITLE
modus-vivendi vs ef-dark

### ISSUE THREAD

**Issue by mfuchs1** [protesilaos/modus-themes#46]
Hello @protesilaos 

with the last update of modus-themes I noticed these grey borders within modus-vivendi. I load the theme with

``` elisp
(load-theme 'modus-vivendi t)
```
![modus-vivendi](https://user-images.githubusercontent.com/24796328/197380995-97c45818-fa3f-46a3-9496-aaeb8e7a437e.png)

These grey borders are shown with modus-operandi, too.

I changed the theme to ef-dark (or any other ef-theme):

``` elisp
(load-theme 'ef-dark t)
```

and there are no grey borders:

![ef-dark](https://user-images.githubusercontent.com/24796328/197381036-f971f1a0-bdf5-421a-acfc-cc4d527b0219.png)

I don't know what may have caused this issue within modus-vivendi and modus-operandi.

Thanks a lot for your great work. This week we have holidays in Austria so I will have time to send you this email about philosophy.
Have a nice day,
Matthias

**Comment by mfuchs1** [comment]
Sorry, dear @protesilaos 

I made some mistakes in my first post #45 - so I deleted its content. I'm sorry.

**Comment by protesilaos** [comment]
Good day @mfuchs1!

This is an intended change.  I published an announcement earlier today: https://protesilaos.com/codelog/2022-10-23-breaking-modus-themes-3-0-0-notice/

You can disable it by adding this to your configuration:

```elisp
(setq modus-themes-fringes nil)
```

Add it before the call to load `modus-vivendi`.  If you customise variables some other way, please let me know and I will help you set it up properly.

**Comment by protesilaos** [comment]
No worries about the other post.

**Comment by protesilaos** [comment]
Since you are using the `olivetti` package, notice I will add a new change now that covers its `olivetti-fringe` face: I will make it invisible.

**Comment by mfuchs1** [comment]
> Since you are using the `olivetti` package, notice I will add a new change now that covers its `olivetti-fringe` face: I will make it invisible.

Okay - that's great. And thanks for the link to your announcement: now I'm able to understand these changes.

**Comment by protesilaos** [comment]
You are welcome!  I published the change to cover the `olivetti-fringe`.  It will be available once the package is rebuilt.  Maybe a couple of hours from now.

**Comment by protesilaos** [comment]
Hello again @mfuchs1!  Did you have the chance to check the latest version of the themes?  Does it fix the problem you had with the visible fringes?

**Comment by mfuchs1** [comment]
Hello @protesilaos 

I was checking the latest version of the modus-themes - and the fringes in olivetti-mode are still there. I didn't add 
``` emacs-lisp 
(setq modus-themes-fringes nil)
``` 
to my init.el.

**Comment by mfuchs1** [comment]
Hello @protesilaos 

I've checked the settings in Emacs - I found "olivetti fringes" 
![Olivetti Fringe](https://user-images.githubusercontent.com/24796328/197610643-4d369c58-462f-4c4f-9938-306c2a2d1b61.png)

**Comment by protesilaos** [comment]
Hello @mfuchs1!  The underlying issue was that Olivetti would still read the generic fringe attributes, even though the `olivetti-fringe` had no background of its own.  Anyhow, I made it explicitly use the main background, so it will be invisible now.

```
commit 638e92c4811ece5753ed8d7dccc1ce23983ba70c
Author: Protesilaos Stavrou <info@protesilaos.com>
Date:   Tue Oct 25 19:44:20 2022 +0300

    Make olivetti-fringe use the main background
    
    The previous style did not actually hide the fringes, as olivetti
    would still fall back to reading the generic fringe face.
    
    The intent of this change is to make the olivetti-fringe invisible.
    
    Thanks to Matthias Fuchs for reporting the issue that helped me track
    this problem.  This was done in issue 46 on the GitHub mirror:
    <https://github.com/protesilaos/modus-themes/issues/46>.

 doc/modus-themes.info | 40 ++++++++++++++++++++--------------------
 doc/modus-themes.org  | 26 +++++++++++++-------------
 modus-themes.el       |  2 +-
 3 files changed, 34 insertions(+), 34 deletions(-)
```

**Comment by mfuchs1** [comment]
Hello @protesilaos 
sorry for this post late in the night. I've updated the modus-themes and I can confirm that the fringes in olivetti mode are invisible now. A BIG thank you for your great work :-) Good Night.

**Comment by protesilaos** [comment]
Thank you @mfuchs1!  We can safely close this now.
