### ISSUE TITLE
Using `modus-theme-toggle` causes my `org-capture` templates to disappear

### ISSUE THREAD

**Issue by hapst3r** [protesilaos/modus-themes#49]
Hej prot :)

After being confused for quite a while as to why suddenly my `org-capture`-templates are gone, I just realized this is due to my switching between `modus-vivendi` and `modus-operandi`.

Curiously, while those templates defined in a separate file with separate `(use-package ...)` declaration disappear, the template defined in `custom-set-variables` is still there after a theme switch.

This is the code of my `(use-package)` declaration, and an utility function which I don't know is at all related to this (but the more information the better I guess).

```
(defun org-sort-agenda-files-after-capture ()
  (mapcar #'(lambda (file)
	      (with-current-buffer (find-file file)
		(mark-whole-buffer)
		(org-sort-entries nil ?p)
		(save-buffer)
		(kill-buffer)))
	  org-agenda-files))

(use-package org-capture
  :straight nil
  :config
  (setq org-capture-bookmark nil)
  (setq org-capture-templates
	'(("d" "TO[D]O" entry (file "~/notes/org/todos.org")
	   "* TODO [#%^{Prio, A-C}] %^{Inhalt} %^g"
	   :prepend t
	   :empty-lines-before 1)
	  ("t" "[T]agebuch" entry (file "~/notes/org/tagebuch.org")
	   "* *%^{Ort}*, %T\n%?"
	   :prepend t
	   :empty-lines-after 1)
	  ("z" "[Z]itat" entry (file "~/notes/org/zitate.org")
	   "* %^{Zitat}\n:PROPERTIES:\n:Autor:in: %^{Autor:in}\n:Ursprung: %^{Ursprung}\n:END:"
	   :prepend t
	   :empty-lines-after 1)))
  :bind
  ("C-c c" . org-capture)
  :hook
  (org-capture-after-finalize . org-sort-agenda-files-after-capture))
```

Have a good day :)

**Comment by protesilaos** [comment]
Hello @hapst3r!

The only reasonable explanation I can come up with is that the `modus-themes-toggle` ultimately calls this:

```elisp
(mapc #'disable-theme custom-enabled-themes)
```

Because `use-package` wants to store its values as a "theme", the toggle has the effect of disabling everything that `use-package` has stored.

Until we have a more refined `disable-theme`, you will have to try setting this to nil:

```elisp
(defcustom use-package-use-theme t
  "If non-nil, use a custom theme to avoid saving :custom
variables twice (once in the Custom file, once in the use-package
call)."
  :type 'boolean
  :group 'use-package)
```

Does that work?

**Comment by protesilaos** [comment]
Just to note that in the current git HEAD, I no longer use this:

```elisp
(mapc #'disable-theme custom-enabled-themes)
```
