### ISSUE TITLE
Getting an error from load-theme:  byte-code: Wrong number of arguments: (8 . 10), 11

### ISSUE THREAD

**Issue by notImposterSyndromeIfImposter** [protesilaos/modus-themes#5]
Sorry I'm a relative newb to elisp so I don't really understand what the issue is.  But within modus-themes-load-themes, you seem to call (load-theme 'modus-vivendi t t).  This makes sense looking at the function definition, but when I try to evaluate that, I get byte-code: Wrong number of arguments: (8 . 10), 11.

When I evaluate (load-theme 'modus-vivendi) it loads absolutely fine.  Is there something else I can provide to help debug?  Any thoughts on what the issue is?

log from direct evaluation:

```
Debugger entered--Lisp error: (wrong-number-of-arguments (8 . 10) 11)
  modus-themes--mode-line-attrs("#f4f4f4" "#323232" "#e0e6f0" "#323232" "#ffffff" "#2a2a66" "#a8a8a8" "#323232" alt-style nil "#000000")
  byte-code("\306\307!\203\34\0\10\203\34\0\310\10!\311\312\11\"\232\203\34\0\307\313\314\"\204 \0\315\313!\210\316\317\320\321#\210\322\323\317!\324\325\2\"\324\326\3\"..." [load-file-name data-directory modus-themes-scale-4 modus-themes-scale-3 modus-themes-scale-2 modus-themes-scale-1 fboundp require-theme file-name-directory expand-file-name "themes/" modus-themes t require custom-declare-theme modus-vivendi modus-vivendi-theme "Accessible and customizable dark theme (WCAG AAA s..." ((class color) (min-colors 89)) modus-themes--palette alist-get bg-main fg-main bg-dim fg-dim bg-alt fg-alt bg-active fg-active bg-inactive fg-inactive bg-active-accent bg-special-cold fg-special-cold bg-special-mild fg-special-mild bg-special-warm fg-special-warm bg-special-calm fg-special-calm red red-alt red-alt-other red-faint red-alt-faint red-alt-other-faint green green-alt green-alt-other green-faint ...] 2891)

```

**Comment by protesilaos** [comment]
Hello @notImposterSyndromeIfImposter

> Sorry I'm a relative newb to elisp so I don't really understand what the issue is. 

No worries.  We will figure it out.

> log from direct evaluation:

Seems like an error on my end.  Let me check.

**Comment by protesilaos** [comment]
The problem is with an internal function that I edited earlier: `modus-themes--mode-line-attrs`.  I changed the number of arguments it accepts from 11 (9 and 2 optional) to 10 (8 and 2, respectively).  Looking at the code again, everything seems to be in order.

What prompted this error?  Did you just update from MELPA or are you using some other package?

**Comment by notImposterSyndromeIfImposter** [comment]
Yes, just a list-packages + an update.

**Comment by protesilaos** [comment]
I will check again in a pristine environment.  Can you restart Emacs in the meantime? Just to be sure that no old code is affecting things.

**Comment by notImposterSyndromeIfImposter** [comment]
LGTM.  I had to go into list-packages and delete modus-themes to get it working again on reload.  It's possible I used package-install in the past before I learned to use use-package so I'm not sure if that caused issues.  In any event this is fixed now.  Thank you for the fix, the great theme(s) and the videos.  Invaluable stuff.

**Comment by protesilaos** [comment]
I cannot reproduce the bug.  Here is what I did.

1. Just downloaded the latest package from MELPA.
2. Went to my Emacs directory and searched for the package's files.  Mine are stored in `~/.emacs.d/elpa/modus-themes-20210728.1225/`.
3. I opened that directory with `dired` and moved the point to the `modus-themes.el` file.
4. I copied the full path of the file with `C-u 0 w` (or just `0 w`).
5. Opened a shell prompt and typed `emacs -Q` to test things without my configurations.
6. Inside of the new frame's scratch buffer, I inserted this (you need to change the `require` path to yours:

```elisp
(require 'modus-themes "/home/prot/.emacs.d/elpa/modus-themes-20210728.1225/modus-themes.el")
(load-theme 'modus-vivendi t)
```

7. Evaluate the forms.  The theme loaded properly.

![Screenshot from 2021-07-28 20-22-17](https://user-images.githubusercontent.com/12828033/127368049-9dcfeb1e-a25f-44e4-ba1f-6af9d11f4918.png)

**Comment by protesilaos** [comment]
> LGTM. I had to go into list-packages and delete modus-themes to get it working again on reload. It's possible I used package-install in the past before I learned to use use-package so I'm not sure if that caused issues. In any event this is fixed now.

Okay, I just added a message as well.  All good then.

> Thank you for the fix, the great theme(s) and the videos. Invaluable stuff.

Thank you for your time and kind words!
