### ISSUE TITLE
Debian aptitude not show well in term

### ISSUE THREAD

**Issue by tumashu** [protesilaos/modus-themes#51]
Aptitude menu background color is ansi-color-blue and foreground color is ansi-color-white, it is not look good in modus-vivendi

Other info: https://codeberg.org/akib/emacs-eat/issues/12

**Comment by tumashu** [comment]
![图片](https://user-images.githubusercontent.com/67725/205216260-345fa014-80ba-4423-ac39-5105841f1fdc.png)

**Comment by tumashu** [comment]
nmtui 

![图片](https://user-images.githubusercontent.com/67725/205216519-8c79008e-b1af-44f8-bc21-b7010d59d869.png)

**Comment by protesilaos** [comment]
Hello @tumashu!

This is a common problem with various TUI programs: they hardcode colours.  More generally, terminal emulators do not give us the option to define which colour should be used ONLY for backgrounds.  So we define colours for foregrounds/text and then the TUI programs use those however they want.  Often the effect is bad like in your screenshots.

All the faces we have are here:

- ansi-color-black
- ansi-color-blue
- ansi-color-bold
- ansi-color-bright-black
- ansi-color-bright-blue
- ansi-color-bright-cyan
- ansi-color-bright-green
- ansi-color-bright-magenta
- ansi-color-bright-red
- ansi-color-bright-white
- ansi-color-bright-yellow
- ansi-color-cyan
- ansi-color-faint
- ansi-color-fast-blink
- ansi-color-green
- ansi-color-inverse
- ansi-color-italic
- ansi-color-magenta
- ansi-color-red
- ansi-color-slow-blink
- ansi-color-underline
- ansi-color-white
- ansi-color-yellow

None of them are specifically for backgrounds, indicating that this is not in the control of Emacs but the underlying TUI.

This actually is one of the major reasons I moved away from TUI programs and started using Emacs.

**Comment by tumashu** [comment]
wow, new knowledge, thanks very much :-)

**Comment by protesilaos** [comment]
You are welcome!

**Comment by AkibAzmain** [comment]
Great explanation, @protesilaos!  I tried to use different faces for foreground and background, but it was a maintenance burden.

**Comment by protesilaos** [comment]
@AkibAzmain You will get the same problems if you try to tweak the colours of, say, GNOME Terminal.  Terminal emulators expose the first sixteen escape sequences but they do not provide for an abstract way to define the foreground.  Something like Debian's `apt` program has its progress bar hardcoded to a green background with a black foreground.  A theme that is light will thus render that bar in an inaccessible colour combination (black against dark green) OR it will use a light green which is then hard to read for text.  Either way, the situation is not good.

**Comment by AkibAzmain** [comment]
@protesilaos I know that better than many other terminal users, since I wrote a terminal emulator, [Eat](https://codeberg.org/akib/emacs-eat).

**Comment by protesilaos** [comment]
@AkibAzmain Fascinating!  I will try it out as soon as possible.

**Comment by tumashu** [comment]
@AkibAzmain is it possible customize faces for a command in eat, for example, when i run aptitude, it use a group of different faces

**Comment by AkibAzmain** [comment]
@tumashu Fantastic idea!  Added on my TODO list.

**Comment by lee-b** [comment]
The problem is that most terminal apps use the basic ANSI escape sequence support that most terminals can handle.  On linux, that means relying on the typical default colors assigned to a linux console (not some fancy xterm with a color theme).  So your color theme should be very similar to those default colors, for compatibility -- changing them significantly, in color OR contrast, will basically make some terminal apps unreadable.

The proper solution is truecolor terminal color support in both the terminal emulator and the apps, so that the apps can specify the exact RGB colors to use, likley according to how they've been themed, regardless of the terminal defaults. Docs can be found here, for example: https://tintin.mudhalla.net/info/truecolor/
