### ISSUE TITLE
Cannot override colors of the rainbow delimiters

### ISSUE THREAD

**Issue by astynax** [protesilaos/modus-themes#54]
Just updated to 4.0.0 and now I have bright colored parens and the "faint" preset doesn't affect them as it was with old "faint" customization. And also I just can't override, say, `rainbow-delimiters-depth-1-face`'s color without changing the `magenta-intense` globally.

**Comment by protesilaos** [comment]
Thank you @astynax!  Just made the necessary changes.  Also to the "faint" preset.  Please give it a try and let me know what you think.  We can make further tweaks, if needed.

**Comment by astynax** [comment]
@protesilaos just updated and tested and it works perfectly! Thank you a lot!

**Comment by protesilaos** [comment]
You are welcome!  Closing now.
