### ISSUE TITLE
A very strange bug, whenever using doom-modeline with icons enabled, bits of the theme background 'spill' onto the icons

### ISSUE THREAD

**Issue by MetalMaxMX** [protesilaos/modus-themes#58]
So this is a really difficult bug for me to explain because I can't, sadly, consistently reproduce it. It behaves akin to an Heisenbug where it may appear or not, it is very minor but I might as well describe the problem (It may also be a windowing bug but I am not so sure about that since this behavior didn't happened with modus-themes 3 I believe) 

I am using modus-themes-4, so this behavior didn't happened to me when using 3. So, what happens is that you install and enable doom-modeline and also enable the icons within doom-modeline. Once enabled, things go fine and all and you can close Emacs. On certain occasions however, the color of the main background may spill onto the icon itself (For example, a regular Emacs startup may have the Lisp icon, and some of the bits are covered in white if using modus-operandi)

I have tried my best in attempting to consistently reproduce the bug but it is difficult, it may only show up occasionally and trying to do a screenshot of it has the bug vanishing away like magic for some reason!  Only to come back down the line later on. 

It is, again, a minor bug, but it is awkward as to why it may suddenly appear or suddenly not. I am not sure if some of the themes are somehow impacting the way the icons in doom-modeline are themed? I could pass my own config and see if the author is able to reproduce this, can't say I mind 

Cheers
MetalMaxMX

**Comment by protesilaos** [comment]
Hello @MetalMaxMX!  Have you made any recent changes to Emacs?  I doubt this is related to the themes as the faces+attributes I use for doom-modeline are standard.  What Modus 4 basically does is rearrange how we apply the colour values.

At any rate, can you share your config with me?  I will give it a try.

**Comment by MetalMaxMX** [comment]
No, I use Emacs 28.2 compiled natively with gcc-jit enabled. I rarely use something from the master branch since I do like the idea of stability :P, or at least, having a big number major version and all functioning. Anyway, here's my config
[emacs.zip](https://github.com/protesilaos/modus-themes/files/10322993/emacs.zip)

(Rename emacs.zip to .emacs as github doesn't like the ideas of text files yet for some reason. Also, do mind that it is a very, very messy config and I touch it sporadically, as I am (kind of?) a newcomer to Emacs (I like staring at code editors yes!)

**Comment by MetalMaxMX** [comment]
Just for wanting to do something. I tried this also with the ef-themes (both light and dark) in the hope to see the bug appearing and yet it doesn't, not even once. Only with modus themes do those issues appear

**Comment by protesilaos** [comment]
Maybe try it with some other theme beside my own?  I suspect it is a doom-modeline issue, though I wan to keep track of this.

**Comment by MetalMaxMX** [comment]
Oh hey, yeah! I did get some weird artifacts using other themes like doom-solarized-light and all, much like it is present in this theme. I suppose is an overall bug in there then. The reason why I was able to spot it quickly with your themes probably has to do with your themes being pretty clear and legible for me to observe and witness! 

Thanks for answering! Not sure what to do now though. Perhaps I'll raise the issue on their repo?

**Comment by protesilaos** [comment]
Yes, the doom-modeline repo seems the right place for this.

**Comment by MetalMaxMX** [comment]
Done! You're free to close the issue now, thanks for answering once again. Cheers!

**Comment by protesilaos** [comment]
Great, thank you!
