### ISSUE TITLE
modus themes and ediff

### ISSUE THREAD

**Issue by bernardjoseph** [protesilaos/modus-themes#68]
Ediff does not use the right faces. Only when diff-mode is loaded, the faces are correct. The problem seems to be that the modus themes faces for ediff inherit faces from diff-mode. But diff-mode is not required by ediff. Without having diff-mode loaded, the faces seem not to be set correctly. If my observations are correct, the same problem can arise in other libraries too.

**Comment by protesilaos** [comment]
Thank you @bernardjoseph!  I just pushed the change.  Please let me know if it works for you.

**Comment by bernardjoseph** [comment]
I think the other inherited ediff faces must be fixed too.

**Comment by bernardjoseph** [comment]
The changes work for me.

**Comment by protesilaos** [comment]
Yes, all ediff faces need to avoid this inheritance.  I updated it now.
