### ISSUE TITLE
Palette-override support for background of the `prose-*` faces?

### ISSUE THREAD

**Issue by okamsn** [protesilaos/modus-themes#69]
The `background` setting for the old `modus-themes-markup` seems to have been left behind from the new palette overrides.

While it is easy to use the normal `set-face-background`, would you be open to adding palette-override support for backgrounds to the prose markup faces?

**Comment by okamsn** [comment]
After thinking it over, I'm not sure that the small benefit justifies the effort in changing this.

**Comment by protesilaos** [comment]
Hello @okamsn!  In principle I am fine with this.  The reason I removed them is that backgrounds are overriden by `hl-line-mode`.  If we rely on them, we sometimes are not able to spot the special text.  More so when `visual-line-mode` is in effect and the user works with long lines.
