### ISSUE TITLE
Misspelled face 'widget-buton'

### ISSUE THREAD

**Issue by steve-downey** [protesilaos/modus-themes#73]
https://github.com/protesilaos/modus-themes/blob/main/modus-themes.el#L3796

 `(widget-button-pressed ((,c :inherit widget-buton :foreground ,fg-link-visited)))

Found while attempting to export faces into css with `M-x org-html-htmlize-generate-css`

Sorry for not having a patch.

**Comment by protesilaos** [comment]
Thank you @steve-downey!  Just pushed the change.
