### ISSUE TITLE
Org heading leading stars not hidden

### ISSUE THREAD

**Issue by pilipovicn** [protesilaos/modus-themes#76]
Hi Prot, thanks for the nice packages!

The problem I have is that in Org mode, the heading stars are not hidden even though I set `org-hide-leading-stars`. This is only a problem with the modus themes, as it works well, for example, with doom themes. 

The stars aren't "reachable" with a cursor, as if they are inside the page margins (can't place a cursor on them, and cant inspect their face).

Here is an example with modus-vivendi-tinted.
![image](https://user-images.githubusercontent.com/37810042/233828309-93082d1c-989d-4644-a49a-ba315f753a91.png)

And here is an example with doom-old-hope.
![image](https://user-images.githubusercontent.com/37810042/233828362-d1351ef0-fe66-402d-9e64-1d0a8756d43b.png)

The thing that gets rid of those stars is disabling `org-indent-mode` that I've enabled, but I'd like not to do that because it looks better with indents.

Here is an example on a modus theme, with `org-indent-mode` disabled.
![image](https://user-images.githubusercontent.com/37810042/233828546-85658334-e829-4492-93cc-af03ad84bea8.png)

This could very well be a weird thing on org-indent' part and not on modus-themes end, or maybe I've messed something up.

**Comment by protesilaos** [comment]
Hello @pilipovicn!

Have you tried to call `org-mode-restart` after changing the value of the `org-hide-leading-stars`?

Here is what I get:

![2023-04-23_13:36:24_1914x1041](https://user-images.githubusercontent.com/12828033/233834992-21b80a59-1091-4024-bf67-95a8144a58d6.png)

![2023-04-23_13:37:22_1914x1041](https://user-images.githubusercontent.com/12828033/233834994-cd579fb7-f196-442c-9386-d88a12f25a25.png)

**Comment by pilipovicn** [comment]
Yes I restart org mode between each variable change. Do you have org-indent-mode turned on? Because I get the same result as you if I turn it off, example below:

![image](https://user-images.githubusercontent.com/37810042/233836821-df6a9814-abd2-45f5-8b41-f40e6f6ec699.png)

But when I turn on `org-indent-mode` it becomes this:
![image](https://user-images.githubusercontent.com/37810042/233836850-0289eddc-14de-4e8c-b194-a15f53bf1935.png)

In both examples, `org-hide-leading-starts` is true. (in these examples I disabled org-superstar package so I could get the same results as you).
Again, for comparison, the doom-old-hope theme does not add the stars when I turn on `org-indent-mode`

**Comment by protesilaos** [comment]
The `org-indent-mode` does not make any difference on my end:

![2023-04-23_14:28:20_1914x1041](https://user-images.githubusercontent.com/12828033/233837169-068d4686-c440-4cae-abaf-f1de9f417f0d.png)

At any rate, the themes set the colour of the "hide" to that of the main background.  The relevant part from `modus-themes.el`:

```elisp
    `(org-hide ((,c :foreground ,bg-main)))
    `(org-indent ((,c :inherit (fixed-pitch org-hide))))
```

Can you try to reproduce your problem with `emacs -Q`?  If you are not sure how to do it, I will write instruction.

**Comment by protesilaos** [comment]
Looking at the code now, have you explicitly set the foreground of the `fixed-pitch` face?

**Comment by pilipovicn** [comment]
Ah, that was it! Didn't know that would mess up the theme. The problematic line was
`(set-face-attribute 'fixed-pitch nil :family "Roboto Mono" :inherit 'default)`
So i removed the inherit part so it doesn't pick up the foreground color from default, and it works now. But now it doesn't inherit the font size either, but I will figure something out. 
I think this is solved now on my end. Thank you for the help!

**Comment by protesilaos** [comment]
Very well!  In general, faces do not need to inherit from `default`.  This is done implicitly for all their missing attributes.
