### ISSUE TITLE
Feature request: theme for eink display

### ISSUE THREAD

**Issue by QiangF** [protesilaos/modus-themes#77]
As the price of eink display goes down, eink monitor is quite accessible for programmers. For example I got this brand ne philisp eink monitor for less than $300 https://goodereader.com/blog/technology/philips-launches-two-in-one-monitor-with-lcd-and-e-ink-panels

And there are many old ebook readers that are perfect eink monitors, such as the boox max 2.

Eink is much better to the eye for coding. modus operandi theme is quite good, except for the colors. Maybe it's time for a theme. The theme should only use bold, itallic fonts, with underline or overline.

**Comment by protesilaos** [comment]
Hello @QiangF!  I don't have access to such hardware.  If it does not use any colours, then we would need to create a new theme instead of modifying the `modus-themes`.
