### ISSUE TITLE
Support of new faces `vundo{-last}-saved`

### ISSUE THREAD

**Issue by nsemrau** [protesilaos/modus-themes#79]
Prot, after much switching I landed on the modus-themes for good. The amount of thought that went into them regarding contrast and accessibilty combined with breadth of the supported packages really make them a shining beacon in the world of Emacs themes. Thank you! :smile: 

---

The already supported Vundo (visual undo) just released a new version. It now defines `vundo-saved`. This highlightes saved states in the undo chain.

Unfortunately, the highlight is a green color and looks hard to differentiate against unsaved states coloured in black in `modus-operandi-tinted` (my favourite theme):

![mo](https://user-images.githubusercontent.com/4363876/236902664-9fdcf2fa-9e91-4aa2-bbc9-64d99b18ccd7.png)

The effect really is noticable when you have a longer chain and you see of the hihjlighted dots only in your peripheral vision. It is slighly better in `modus-operandi`.

In `modus-vivendi-tinted`, the dark background is helping. The dots are better to differentiate against the dark background:

![mv](https://user-images.githubusercontent.com/4363876/236905123-6fc89426-4e79-4bae-930d-63c4950ec399.png)

`vundo-last-saved` also got defined. This sets an additional bold face on the green highlight. Maybe these faces would look more noticable/distinct in the chain, if you defined a colour from the standard modus colourspace for `vundo-saved`.

**Comment by protesilaos** [comment]
Hello @nsemrau!  Yes, we can support this new face.  I think a blue colour will stand out more.

Can you tell me what I need to do to save a state?  Is it when the file is saved, or some specific arrangement the user has to make?

**Comment by nsemrau** [comment]
Oh, sorry, I should have been more clear about that. "Saving state" means the normal `save-buffer` in Emacs. A regular black dot, representing a step in the editing process, turns to green/`vundo-saved` in order to represent a saved-to-disk status of the buffer.

**Comment by protesilaos** [comment]
Thank you!  I just added support for them.  I picked a cyan colour.  Please let me know if that works for you.  We can tweak it further if necessary.

**Comment by protesilaos** [comment]
I admit that I do not like the current style.  It can be too subtle, depending on the fonts.  The alternative is to use background colours.  Though I am not sure about this either, as it does not look as pretty.

What do you think of these?

![2023-05-08_22:25:47_198x78](https://user-images.githubusercontent.com/12828033/236914788-ee8fa12b-b72b-4c69-812b-4b2b398f7673.png)

![2023-05-08_22:25:22_186x90](https://user-images.githubusercontent.com/12828033/236914783-f438e10f-cdb5-4bb2-b155-7922e0a3478a.png)

![2023-05-08_22:25:54_192x82](https://user-images.githubusercontent.com/12828033/236914790-88637cc7-e64d-48e9-883d-2e7db44b49c3.png)

![2023-05-08_22:25:39_192x81](https://user-images.githubusercontent.com/12828033/236914785-74ab0559-5e21-4ea6-a041-3be8bda5ca3e.png)

**Comment by protesilaos** [comment]
> I like the look of your last changes - the dots are very dishtinguishable between normal and saved state for me as an average-sighted person. The issue is solved from my point of view.

Thank you!

> But that is just my gut feeling without any knowledge in this field.)

You are right.  I am not entirely happy with it.  I have been using it, but need to think of a different way to approach this.  I experimented with using the main foreground for the saved states.  The other nodes would be left to the lighter grey.  It works.  What I am not sure about is how a user goes about using this.  Are they relying more on the tree or are they also checking the buffer to see how the contents are affected?  Colour coding those states depends on their significance in the workflow, which is not clear to me.

**Comment by protesilaos** [comment]
This is done, by the way.  I forgot to close the issue.  Doing it now.  Thank you!
