### ISSUE TITLE
How to modify org-habit background color

### ISSUE THREAD

**Issue by morgandavidson** [protesilaos/modus-themes#81]
I'm using `modus-vivendi-deuteranopia` and `modus-operandi-deuteranopia`.  I found `modus-vivendi-deuteranopia` main text color too white so I modified it (see below). I also tried to modify org-habit background color, but it didn't work:
```
(setq modus-vivendi-deuteranopia-palette-overrides
	  '((fg-main "#e1dfeb")
           (blue-graph-1-bg bg-main)))
```
What am I doing wrong?

**Comment by protesilaos** [comment]
Hello @morgandavidson!

The name of the blue graph is `bg-graph-blue-1`:

```elisp
(setq modus-vivendi-deuteranopia-palette-overrides
	  '((fg-main "#e1dfeb")
        (bg-graph-blue-1 bg-main)))
```

**Comment by morgandavidson** [comment]
Hello protesilaos!
Thank you, it works fine now. I got the wrong name [here](https://protesilaos.com/codelog/2022-01-02-review-modus-themes-org-habit-colours/).

**Comment by protesilaos** [comment]
Oh, I see.  Blog posts become outdated.  The up-to-date resource is the manual.  The [section that introduces palette overrides](https://protesilaos.com/emacs/modus-themes#h:34c7a691-19bb-4037-8d2f-67a07edab150) makes a reference to the command `modus-themes-list-colors`, which is then [explained at greater length](https://protesilaos.com/emacs/modus-themes#h:f4d4b71b-2ca5-4c3d-b0b4-9bfd7aa7fb4d).  That command will help you get the names of the colours and also preview their colour value.

Please let me know if that works for you.

**Comment by morgandavidson** [comment]
Yes it works perfectly, thank you! `M-x modus-themes-list-colors` is very useful indeed.
