### ISSUE TITLE
[Question] Will `modus-themes` integrate with `doom-modeline` in the future?

### ISSUE THREAD

**Issue by david-alvarez-rosa** [protesilaos/modus-themes#83]
Just a question — should we expect `modus-themes` to integrate with `doom-modeline` at any time in the future?

**Comment by protesilaos** [comment]
`doom-modeline` is already supported.  Maybe there is a problem with it?

**Comment by david-alvarez-rosa** [comment]
My bad, @protesilaos, did not know it. This is awesome! Thanks :)
