### ISSUE TITLE
High modeline bar for org and elisp mode

### ISSUE THREAD

**Issue by pati-ni** [protesilaos/modus-themes#84]
The mode line is unusually high for some major modes but not all of them. Is this caused by modus themes and if so, is there a way to remove this customization?

![minifridge-2023-06-25_00:51:43-emacs-3833x284](https://github.com/protesilaos/modus-themes/assets/14965608/b5115012-12ea-4b5b-8cae-f3384a31a11d)

**Comment by protesilaos** [comment]
Hi @pati-ni!  You seem to be using the `doom-modeline` package.  It has a new dependency on the `nerd-icons`.  You thus need to install the icon files with `M-x nerd-icons-install-fonts`.

**Comment by pati-ni** [comment]
Hi prot,

yep, this worked nicely. I will close this ticket now. Thanks for the help!

**Comment by protesilaos** [comment]
You are welcome!
