### ISSUE TITLE
embark-isearch-highlight-indicator on modus-operandi

### ISSUE THREAD

**Issue by ktfleming** [protesilaos/modus-themes#86]
Hi Prot,

By default, Embark's `embark-indicators` is set to `(embark-mixed-indicator embark-highlight-indicator embark-isearch-highlight-indicator)`. Regarding the last two, the docstring for `embark-isearch-highlight-indicator` says this:

> This indicator only does something for targets which are
identifiers or symbols.  For those it uses isearch's lazy
highlighting feature to highlight all occurrences of the target in
the buffer.  This indicator is best used in conjunction with
embark-highlight-indicator: by using them both you get the
target and the other occurrences of it highlighted in different
colors.

However, with the default colors for `modus-operandi`, this effect ("you get the target and the other occurrences of it highlighted in different colors") is not really apparent. Here's a screenshot of some code from Emacs's `xdisp.c`: 
<img width="567" alt="Screen Shot 2023-07-05 at 21 49 40" src="https://github.com/protesilaos/modus-themes/assets/3702988/c6190f95-fb40-455e-a844-3b40417089dd">

I've put the point on one of the `area` identifiers and called `embark-act`. After doing so, the other `area` identifiers are highlighted. They're actually using different faces with slightly different colors, but to me they look like essentially the same color. The one under the point uses the face `embark-target` which inherits from `highlight` which in `modus-operandi` is `#94d4ff`. Meanwhile I believe the other identifiers use the `lazy-highlight` face, which is `#a4d5f9` (cyan-intense).

Compare to using Isearch, where the "current" and "other" matches are quite different:
<img width="580" alt="Screen Shot 2023-07-05 at 21 59 15" src="https://github.com/protesilaos/modus-themes/assets/3702988/cc584d94-3afa-45aa-94c1-fcb0a1f44c3a">

In `modus-vivendi` the two faces are a bit more distinguishable, although still fairly close to my eyes:
<img width="569" alt="Screen Shot 2023-07-05 at 21 57 31" src="https://github.com/protesilaos/modus-themes/assets/3702988/14c98a3f-9cec-47c5-baf3-664d9b1b52b1">

I'm not sure what the best approach is, but it would be nice if these two faces were more immediately distinguishable (like when using Isearch).

**Comment by protesilaos** [comment]
Hello @ktfleming!  This is a tricky case.  On the one hand, it makes sense for Embark to highlight the target with the `highlight` face.  On the other, using the isearch lazy highlights is not consistent with how isearch uses those as its current match is yellow.  We may thus need to revise the Embark face.

At any rate, I just pushed commit `4e331d2` which revises the colour that Embark uses for the current target.  If that is enough, then we don't make any further changes.  What do you think?

**Comment by ktfleming** [comment]
> At any rate, I just pushed commit 4e331d2 which revises the colour that Embark uses for the current target. If that is enough, then we don't make any further changes. What do you think?

It looks good to me now -- thank you!

**Comment by protesilaos** [comment]
Very well!  The other option would be to make Embark look like isearch, though I tried it and it feels a bit strange, especially for larger portions of text.
