### ISSUE TITLE
Support `corfu-candidate-overlay` package faces

### ISSUE THREAD

**Issue by nsemrau** [protesilaos/modus-themes#89]
The completion popu package `corfu` gained the add-on package `corfu-overlay-mode`. Instead of popping up a completion pop-up, it now previews one completion candidate in a lighter face after the to-be-completed symbol ([Picture](https://code.bsdgeek.org/adam/corfu-candidate-overlay/#user-content-headline-2)).

It defines these faces:

```elisp
(defface corfu-candidate-overlay-face
  '((((background light))
     :foreground "MistyRose4")
    (((background dark))
     :foreground "wheat"))
  "Face used for the overlay with the first candidate.")

(defface corfu-candidate-overlay-face-exact-match
  '((t (:inherit 'corfu-candidate-overlay-face :underline t)))
  "Face used for the overlay when there is only one candidate.")
```

While the faint yellowish `wheat` tone in `modus-vivendi-tinted` is quite acceptable for me in the readability department as a average-sighted person, official support for this neat package with a color from the Modus pallete would be great.

**Comment by protesilaos** [comment]
Hello @nsemrau!  I just added support for the relevant face.  I made it inherit from `shadow`, so it will appear gray.  Please let me know if this works for you.

**Comment by nsemrau** [comment]
I tested the change against light and dark Modus themes. I find it quite homourous that the "shadow" of a possible completion is expressed by the face attribute "shadow". :D

The version against is super legible. While losing a hint of brightness when going from `wheat` to `shadow`, I think it expresses the raison d’être of this package even better now. Thank you for your quick and improving change!

**Comment by protesilaos** [comment]
You are welcome!
