### ISSUE TITLE
Typo in docstring of `modus-themes-preset-overrides-intense`

### ISSUE THREAD

**Issue by nsemrau** [protesilaos/modus-themes#90]
https://github.com/protesilaos/modus-themes/blob/b23c84e6b44e13ed12758eda05ab9d5f75928315/modus-themes.el#L1032 in the docstring of `modus-themes-preset-overrides-intense` seems to be a copy-and-insert error copied over from `modus-themes-preset-overrides-faint`'s docstring.

**Comment by protesilaos** [comment]
Sorry for the late reply!  I had no regular access to the Internet.
It's all good now.

> From: Nicolas Semrau ***@***.***>
> Date: Tue,  5 Sep 2023 16:09:44 -0700
>
> In `modus-themes-preset-overrides-intense`
> https://github.com/protesilaos/modus-themes/blob/b23c84e6b44e13ed12758eda05ab9d5f75928315/modus-themes.el#L1032
> says: `Preset for palette overrides with faint coloration`. This seems
> to be a copy-and-paste error inherited from
> `modus-themes-preset-overrides-faint`.

Thank you!  I just pushed the change.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by nsemrau** [comment]
Thanks!
