### ISSUE TITLE
[Windows] Org indent mode broken?

### ISSUE THREAD

**Issue by ntrocado** [protesilaos/modus-themes#91]
Steps to reproduce:
1. emacs.exe -Q
2. create an org file with the following content:
![image](https://github.com/protesilaos/modus-themes/assets/10780358/d1d3f751-d6d5-4036-add6-40844cc86325)
3. `M-x org-indent-mode` produces:
![image](https://github.com/protesilaos/modus-themes/assets/10780358/7db221ef-87ac-484b-9ac7-77250c8e3067)
4. After `M-x load-theme RET modus-operandi`:
![image](https://github.com/protesilaos/modus-themes/assets/10780358/b04caf4f-6d53-44f9-8ffa-4d5333962938)

The problem is that text is not horizontally aligned under each subheading.

Emacs version is `GNU Emacs 29.1 (build 2, x86_64-w64-mingw32) of 2023-07-30` under Windows10.

(Sorry for the large images)

**Comment by protesilaos** [comment]
> From: Nuno Trocado ***@***.***>
> Date: Thu,  9 Nov 2023 07:18:20 -0800
>
> Steps to reproduce:
> 1. emacs.exe -Q
> 2. create an org file with the following content:
> ![image](https://github.com/protesilaos/modus-themes/assets/10780358/d1d3f751-d6d5-4036-add6-40844cc86325)
> 3. `M-x org-indent-mode` produces:
> ![image](https://github.com/protesilaos/modus-themes/assets/10780358/7db221ef-87ac-484b-9ac7-77250c8e3067)
> 4. After `M-x load-theme RET modus-operandi`:
> ![image](https://github.com/protesilaos/modus-themes/assets/10780358/b04caf4f-6d53-44f9-8ffa-4d5333962938)
>
> The problem is that text is not horizontally aligned under each subheading.

What is the font family of the 'fixed-pitch' face? Check it with M-x
describe-face.

It seems that it is not monospaced or, anyhow, defaults to an
inappropriate value.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by ntrocado** [comment]
You're right, there seems to be something wrong with my system:
![image](https://github.com/protesilaos/modus-themes/assets/10780358/e873a151-52e5-4a98-a6e9-caa316a0a0f2)

I don't know how emacs picks the default fonts. Any idea how to fix this?

**Comment by protesilaos** [comment]
> From: Nuno Trocado ***@***.***>
> Date: Sat, 11 Nov 2023 06:37:10 -0800
>
> You're right, there seems to be something wrong with my system:
> ![image](https://github.com/protesilaos/modus-themes/assets/10780358/e873a151-52e5-4a98-a6e9-caa316a0a0f2)
>
> I don't know how emacs picks the default fonts. Any idea how to fix this?

You can specify your preferred font family with what is described here:
<https://protesilaos.com/emacs/modus-themes#h:defcf4fc-8fa8-4c29-b12e-7119582cc929>.

Excerpt:

    ;; Main typeface
    (set-face-attribute 'default nil :family "DejaVu Sans Mono" :height 110)

    ;; Proportionately spaced typeface
    (set-face-attribute 'variable-pitch nil :family "DejaVu Serif" :height 1.0)

    ;; Monospaced typeface
    (set-face-attribute 'fixed-pitch nil :family "DejaVu Sans Mono" :height 1.5)

Please let me know how it goes.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by ntrocado** [comment]
Works perfectly, thanks!

**Comment by protesilaos** [comment]
> From: Nuno Trocado ***@***.***>
> Date: Fri, 17 Nov 2023 05:44:50 -0800
>
> Works perfectly, thanks!

You are welcome!

-- 
Protesilaos Stavrou
https://protesilaos.com
