### ISSUE TITLE
Error loading modus-operandi-tritanopia

### ISSUE THREAD

**Issue by rhstanton** [protesilaos/modus-themes#92]
Starting today, when I load this theme in init.el, I get the following error:

Debugger entered--Lisp error: (error "Face height does not produce a positive integer")
  set-face-attribute(modus-themes-heading-8 #<frame emacs 0x7fb23713be30> :inherit nil :background unspecified :foreground "#595959" :overline unspecified :height nil :weight semilight)
  face-spec-set-2(modus-themes-heading-8 #<frame emacs 0x7fb23713be30> (:inherit nil :background unspecified :foreground "#595959" :overline unspecified :height nil :weight semilight))
  face-spec-recalc(modus-themes-heading-8 #<frame emacs 0x7fb23713be30>)
  custom-theme-recalc-face(modus-themes-heading-8)
  enable-theme(modus-operandi-tritanopia)
  load-theme(modus-operandi-tritanopia t)

**Comment by protesilaos** [comment]
Thank you @rhstanton! I just pushed a change. Please let me know if it fixes the issue on your end.

**Comment by rhstanton** [comment]
Works now. Thanks!
