### ISSUE TITLE
 should probably unify the colors of `imenu-list-entry-subalist-face` and `menu-list-entry-face`

### ISSUE THREAD

**Issue by ltmsyvag** [protesilaos/modus-themes#95]
Modus lover here!

The imenu-list face settings in `modus-themes.el`, namely:
https://github.com/protesilaos/modus-themes/blob/5a777c30ca9f915e97ffd394736a4d547a8899e4/modus-themes.el#L2647-L2654
set 8 different colors for 8 different imenu-list faces, but this is causing visual confusion. Because in fact, an imenu-list entry `imenu-list-entry-subalist-face-<num>` is at the same level as `imenu-list-entry-face-<num>` (they have the same `<num> `!), the only difference is that the former contains sub-entires. 

The modus-vivendi colorization of imenu-list now looks like:
![Screenshot 2024-01-04 at 18 05 53](https://github.com/protesilaos/modus-themes/assets/29622362/9fd9131c-6281-4b5f-8f52-e47f9ed3f1d9)
which is confusing, because "Earth" is at the same level as Venus, but it has a different color. What's NOT confusing would look like below:
![Screenshot 2024-01-04 at 18 03 21](https://github.com/protesilaos/modus-themes/assets/29622362/94d93ed4-b923-4123-8ee0-d4d7e82a1857)

Without modus-themes, the above is also the default behavior of imenu-list, which I produce below with a vanilla-ish emacs:
![Screenshot 2024-01-04 at 18 28 39](https://github.com/protesilaos/modus-themes/assets/29622362/de3eb4d6-6c50-410d-be09-e5ceff96586f)

**Comment by protesilaos** [comment]
Thank you @ltmsyvag! You are right. I don't remember why it was with eight colours before. Just made the change.
